### ISSUE TITLE
Is it possible to group a column based on another field value?

### ISSUE THREAD

**Issue by fingers10** [ClosedXML/ClosedXML.Report#101]
I'm trying to generate report as shown below. Is this possible? Please assist.

Let's say I have `List<Product>` where `Product` is,

```c#
public class Product
{
    public string Category {get: set;}
    public string Name {get; set;}
}
```

Now I want to do grouping based on `Category` but display `Name` in that column. Can this be done?

![image](https://user-images.githubusercontent.com/43729469/63427954-f7b94080-c433-11e9-9117-02be362b74c1.png)

As you can see I have `Name` as column header and that should display `Name` but group by `Category` and display that as summary.

**Comment by b0bi79** [comment]
You need to use the `placetocolumn` parameter for the `group` tag, as well as the `Delete` tag.
It will look something like this:
`<<group MergeLabels placetocolumn=2>><<Delete>>`
You can see an example of such a report here [Specifying the Location of Group Captions](https://closedxml.github.io/ClosedXML.Report/docs/en/Examples#specifying-the-location-of-group-captions)

**Comment by fingers10** [comment]
Yeah that works. Thanks.

I have another query. Is it possible to suppress the value in particular column inside a group and instead place them on group header?

Let's say we have another column in the `Product` class named `PurchasedFrom` and this column has same values for all the rows inside the group. So I would like to suppress the value in cells for all rows inside the group and like to place it on the cell in group header. Can we do that here?

**Comment by b0bi79** [comment]
You can do it as described [here](https://stackoverflow.com/a/9174254/498202) or write your own tag inherited from `OptionTag`

**Comment by fingers10** [comment]
any documentation for what is `OptionTag`?

**Comment by b0bi79** [comment]
[OptionTag Class](https://github.com/ClosedXML/ClosedXML.Report/blob/develop/ClosedXML.Report/Options/OptionTag.cs)
[Implementation example](https://github.com/ClosedXML/ClosedXML.Report/blob/develop/ClosedXML.Report/Options/OnlyValuesTag.cs)

**Comment by b0bi79** [comment]
If you decide to write your tag, you will need to register it like
`TagsRegister.Add<YourTagClass>("YourTagName", 40);`
После этого ты сможешь его применять в шаблоне так: `<<YourTagName>>`

**Comment by b0bi79** [comment]
As a third option, I can propose to process the document after generation.
```
        var template = new XLTemplate(@".\Templates\report.xlsx");

        template.AddVariable(cust);
        template.Generate();
        var sheet = template.Workbook.Worksheet(1);
        sheet....

        template.SaveAs(outputFile);
```

But, in my opinion, the first option is the easiest.

**Comment by b0bi79** [comment]
Try using the `group` tag with the parameter `MergeLabels` parameter for the `PurchasedFrom` column. Maybe this will be enough for you.
`<<group MergeLabels=Merge1>>` or `<<group MergeLabels=Merge2>>`

**Comment by fingers10** [comment]
Thanks. Your last suggestion helped me.
