### ISSUE TITLE
Unknown Identifier error while accessing variables inside nested ranges

### ISSUE THREAD

**Issue by fingers10** [ClosedXML/ClosedXML.Report#103]
Hi,

I have the below class,

```c#
public class ExcelReportModel<T>
    {
        public ExcelReportHeader Header { get; set; }
        public IEnumerable<T> Records { get; set; }
        public int DataYear { get; } = Globals.DataYear;
    }
```

Now if I use `DataYear` inside my excel like this `{{DataYear}}` it works. But If I use the same inside any range like `Records` range its not working.  Please assist

Thanks

**Comment by b0bi79** [comment]
You can output `{{DataYear}}` into a cell outside the range (for example, cell `A3`) and collapse the column `A`. After that, you will be able to reference this cell within the range of `$A$3`

**Comment by fingers10** [comment]
Please could you explain more. If I collapse column A then will the excel work with report generation?

Here is my excel - 
[DataYear Test.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3537458/DataYear.Test.xlsx)

**Comment by b0bi79** [comment]
Replace the formula in cell B4 with `=CONCATENATE($C$1," Goals")`

**Comment by fingers10** [comment]
> Replace the formula in cell B4 with `=CONCATENATE($C$1," Goals")`

This gives the following error -  This function does not accept cell ranges as parameters

**Comment by b0bi79** [comment]
try this formula `=$C$1&" Goals"`

**Comment by fingers10** [comment]
@b0bi79 That works. Thanks.

**Comment by fingers10** [comment]
@b0bi79 I have one more question. I'm asking here as I couldn't find a way to contact you. Closed XML Report idea looks great. Can this similar idea be used to Generate PDF using Microsoft Word with some library named ClosedXML.PDF or ClosedXML.Word? Anything like that available already?

**Comment by Pankraty** [comment]
ClosedXML does not yet support rendering to PDF. As for the Word functionality - it is on the earliest stages of development. See https://github.com/ClosedXML/ClosedXML/pull/1260. A contribution is welcome.

**Comment by fingers10** [comment]
Thanks @Pankraty . I'll look on it.
