### ISSUE TITLE
No property or field in type

### ISSUE THREAD

**Issue by joy-sensato** [ClosedXML/ClosedXML.Report#104]
Hi 

I am getting an error in the excel file "No property or field ''  exists in type 'List`1'" . 
Is there any option to pass a data table to the excel template. if yes then it will be of a great help.

**Comment by b0bi79** [comment]
What code are you using? And please send the template.

**Comment by joy-sensato** [comment]
[STUDENT_LIST.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3573114/STUDENT_LIST.xlsx)

Hi 

this is the template file. 

Following is the line of codes  i am using

`System.Data.DataTable oDt = oBL.rptClassSectionStudentList().Tables[0];


				List<stList> oList = new List<stList>();
				foreach (DataRow row in oDt.Rows)
				{
					stList oMOD = new stList();
					oMOD.SL_NO = row["SL_NO"].ToString();
					oMOD.STUDENT_ID = row["STUDENT_ID"].ToString();
					oMOD.ST_FIRST_NAME = row["ST_FIRST_NAME"].ToString();


					oMOD.ST_LAST_NAME = row["ST_LAST_NAME"].ToString();
					oMOD.GENDER_NAME = row["GENDER_NAME"].ToString();
					oMOD.VER_SUBJECT_NAME = row["VER_SUBJECT_NAME"].ToString();


					oMOD.HOUSE_NAME = row["HOUSE_NAME"].ToString();
					oMOD.GROUP_2 = row["GROUP_2"].ToString();
					oMOD.GROUP_3 = row["GROUP_3"].ToString();

					oMOD.ST_COUNT = row["ST_COUNT"].ToString();
					oMOD.INST_NAME = row["INST_NAME"].ToString();
					oMOD.CLASS_NAME = row["CLASS_NAME"].ToString();

					oMOD.SECTION_NAME = row["SECTION_NAME"].ToString();
					oMOD.SUBJECT_NAME = row["SUBJECT_NAME"].ToString();
					oMOD.LOGIN_NAME = row["LOGIN_NAME"].ToString();

					oMOD.GROUP_3_COUNT = row["GROUP_3_COUNT"].ToString();


					oList.Add(oMOD);
				}

				

				template.AddVariable("QLIST", oList);

				

				template.Generate();
				template.SaveAs(fileName);



private class stList
		{
			public string SL_NO { get; set; }
			public string STUDENT_ID { get; set; }
			public string ST_FIRST_NAME { get; set; }
			public string ST_LAST_NAME { get; set; }
			public string GENDER_NAME { get; set; }
			public string VER_SUBJECT_NAME { get; set; }


			public string HOUSE_NAME { get; set; }
			public string GROUP_2 { get; set; }
			public string GROUP_3 { get; set; }
			public string ST_COUNT { get; set; }
			public string INST_NAME { get; set; }
			public string CLASS_NAME { get; set; }
			public string SECTION_NAME { get; set; }
			public string SUBJECT_NAME { get; set; }
			public string LOGIN_NAME { get; set; }

			public string GROUP_3_COUNT { get; set; }

		}



`

**Comment by b0bi79** [comment]
Your template does not meet the requirements. Read it https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

**Comment by joy-sensato** [comment]
Hi. 
Thanks for your help. now i am able to get the data in the template. after the changes the fields in the header portion is not being displayed.  i am attaching the template for reference. 

thanks in advance. 
[STUDENT_LIST.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3573817/STUDENT_LIST.xlsx)

**Comment by b0bi79** [comment]
What code are you using?

**Comment by joy-sensato** [comment]
c#

**Comment by b0bi79** [comment]
You use the variables `{{INST_NAME}}`, `{{CLASS_NAME}}` and `{{SECTION_NAME}}` in the header, but you did not initialize them in the code.
Add to your code:
```
template.AddVariable("INST_NAME", "Inst name");
template.AddVariable("CLASS_NAME", "Class name");
template.AddVariable("SECTION_NAME", "Section name");
```

**Comment by joy-sensato** [comment]
but this fields are in the list also

**Comment by joy-sensato** [comment]
Hi 
Thanks a lot for your help. is there any option where i can pass a datatable instead of the list. 
that will make my life very easy. 

Thanks a lot for your help

**Comment by b0bi79** [comment]
In general, the `AddVariable (string alias, object value)` method can accept a DataTable. Try this: `template.AddVariable (" QLIST ", oDt);`

**Comment by joy-sensato** [comment]
thanks. I tried it and worked. now i have to explore the pivot table options. i have lot of requirements for the pivot table stuff.

**Comment by swapnilbhade** [comment]
I am getting 'No property or field exists in type' error
Langauge is vb.net
Public Function DailyInward(ByVal productId As String, ByVal supplierId As String, ByVal grnid As String) As FileContentResult
        Dim outputFile As String = Path.Combine(Server.MapPath("~/Output"), "dailyInward" + Date.Now.Date + ".xlsx")
        Dim path_1 As String = Path.Combine(Server.MapPath("~/Templates"), "dailyInward.xlsx")
        Dim template = New XLTemplate(path_1)
        Dim conn As New NpgsqlConnection(ConfigurationManager.ConnectionStrings("WMSContext").ToString)
        Dim ds As New DataSet()
        'Dim ds1 As New DataSet()
        Dim adapter As New NpgsqlDataAdapter()
        'Dim adapter1 As New NpgsqlDataAdapter()
        Try
            conn.Open()
            Dim strQuery As String = "SELECT g.id as grn_id, w.name as warehouse_name, g.source_warehouse, s.name as supplier_name, TO_CHAR(g.grn_datetime, 'DD/MM/YYYY') as grn_date,
                                        g.reference_no, TO_CHAR(g.reference_date , 'DD/MM/YYYY') as reference_date, t.name as transporter_name, g.transporter_id,g.transport_receipt_no, 
                                        g.vehicle_no, g.distance_in_km, g.mode_of_transport, g.driver_name, TO_CHAR(g.transport_receipt_date , 'DD/MM/YYYY') as transport_receipt_date, 
                                        v.name as vehicle_type_name, g.vehicle_type,i.item_code,i.item_name , g.grn_no,
                                        gd.inward_rate, gd.serialnumber, gd.batch_no,TO_CHAR(gd.mfg_date , 'DD/MM/YYYY') as mfg_date, 
                                        TO_CHAR(gd.expiry_date , 'DD/MM/YYYY') as expiry_date, gd.received_qty, gd.dc_qty
                                        FROM public.grn_headers g INNER JOIN grn_details gd ON g.id = gd.grn_id and gd.discontinue = false
                                        INNER JOIN warehouses w ON w.id = g.source_warehouse INNER JOIN suppliers s ON s.id = g.supplier_id
                                        INNER JOIN transporters t ON t.id = g.transporter_id INNER JOIN vehicle_types v ON v.id = g.vehicle_type
                                        INNER JOIN items i ON i.id = gd.item_id
                                        where g.discontinue = false  "
            If Not String.IsNullOrWhiteSpace(grnid) Then
                If InStr(1, strQuery, " where ") <= 0 Then
                    strQuery &= " where "
                Else
                    strQuery &= " and "
                End If
                strQuery &= " g.id = " & grnid & " "
            End If
            If Not String.IsNullOrWhiteSpace(productId) Then
                If InStr(1, strQuery, " where ") <= 0 Then
                    strQuery &= " where "
                Else
                    strQuery &= " and "
                End If
                strQuery &= " gd.item_id = " & productId & " "
            End If
            If Not String.IsNullOrWhiteSpace(supplierId) Then
                If InStr(1, strQuery, " where ") <= 0 Then
                    strQuery &= " where "
                Else
                    strQuery &= " and "
                End If
                strQuery &= " g.supplier_id = " & supplierId & " "
            End If

            Dim command1 As New NpgsqlCommand(strQuery, conn)
            adapter.SelectCommand = command1
            adapter.Fill(ds, "GrnDetails")
            If ds.Tables(0).Rows.Count > 0 Then
                Dim wb As New XLWorkbook
                wb.Worksheets.Add(ds.Tables("GrnDetails"), "Customers")
                Dim myName As String = Server.UrlEncode("Test" + "_" + DateTime.Now.ToShortDateString() + ".xlsx")
                Dim Stream As MemoryStream = GetStream(wb) ' The method Is defined below
                'Response.Clear()
                'Response.Buffer = True
                'Response.AddHeader("content-disposition", "attachment; filename=" + myName)
                ' Response.ContentType = "application/vnd.ms-excel"
                'Response.BinaryWrite(Stream.ToArray())
                'Response.End()
                template.AddVariable("item", GetTableRows(ds.Tables("GrnDetails")))
                'template.AddVariable("items", ds.Tables("GrnDetails").Rows.Cast(Of DataRow)())
                template.Generate()
                template.SaveAs(outputFile)
                Process.Start(New ProcessStartInfo(outputFile) With {
                .UseShellExecute = True
                })
            End If
        Catch ex As Exception
            Throw ex
        Finally
            conn.Close()
            conn.Dispose()
            NpgsqlConnection.ClearPool(conn)
        End Try

        'Using db = New DbDemos()
        '    Dim cust = db.customers.LoadWith(Function(c) c.Orders).First()
        '    template.AddVariable(cust)
        '    template.Generate()
        'End Using
    End Function
