### ISSUE TITLE
Current release 0.1.2 has screwed up references

### ISSUE THREAD

**Issue by davija** [ClosedXML/ClosedXML.Report#105]
The release that is out on nuget (0.1.2) currently claims it has a dependency on ClosedXML  >=0.92.1.

However, I am using 0.94.2 (due to some bugfixes that I need) and I am getting reference errors due to how the references are defined in the project (says it must reference version 0.92.1.0).

This is a show-stopper for me as I need the bugfixes in later versions of ClosedXML and would still like to be able to use ClosedXML.Reports (I cannot use a beta version at this point either).

**Comment by davija** [comment]
In attempting to update a fork of this to use 0.94.2, it became clear that this is not compatible with anything but 0.92.1 due to breaking changes in ClosedXML, so I'm going to close this.

**Comment by Pankraty** [comment]
You can build your own release from the current master - it works with ClosedXML `0.95 beta-something` and most of the features are presented (except the formatting of the pivot tables, I suppose).
