### ISSUE TITLE
Pivot Tab error Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by joy-sensato** [ClosedXML/ClosedXML.Report#106]
Hi 

i am getting an error "Specified argument was out of the range of valid values.\r\nParameter name: The cells B0 and XFD1048575 are outside the range 'Sheet1'"

attaching the template for your reference. 

[STUDENT_LIST.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3577510/STUDENT_LIST.xlsx)

**Comment by b0bi79** [comment]
The named range of QLIST should not be `B4:K5`, but `A4:K5`. Check this should help.
Read the documentation here https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables#Vertical-tables

> Each range specifying the vertical table must have at least two columns and two rows. The leftmost column and the bottom row serve to configuration purposes and are treated the special way. After the report is built the service column is cleared, and the service row is deleted if it is empty.

**Comment by joy-sensato** [comment]
Thanks for your help.

i am attaching the template. i want the report format like that. is it possible

thanks in advance. 
[STUDENT_LIST.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3578054/STUDENT_LIST.xlsx)

**Comment by b0bi79** [comment]
Try this
![image](https://user-images.githubusercontent.com/1150085/64323107-7d102980-cfcc-11e9-9714-828297db5db7.png)
Cells A5 - `<<pivot>>`, B5 - `<<data>><<count>>`, F5 - `<<column>>`
As a result, ClosedXML.Report will create a pivot table on a new sheet.

**Comment by joy-sensato** [comment]
hi 
Thanks for your suggestion.

getting the  following error on template.SaveAs(filename)

Value cannot be null.\r\nParameter name: source

thanks

**Comment by b0bi79** [comment]
Put your code in, I'll check it in the evening.

**Comment by joy-sensato** [comment]
Hi

Please find the code below.

`System.Data.DataTable oDt = oBL.rptClassSectionStudentList().Tables[0];


				template.AddVariable("QLIST", oDt);


				template.AddVariable("INST_NAME", oDt.Rows[0]["INST_NAME"]);
				template.AddVariable("CLASS_NAME", oDt.Rows[0]["CLASS_NAME"]);
				template.AddVariable("SECTION_NAME", oDt.Rows[0]["SECTION_NAME"]);
				template.AddVariable("ST_COUNT", oDt.Rows[0]["ST_COUNT"]);

				template.AddVariable("LOGIN_NAME", oDt.Rows[0]["LOGIN_NAME"]);

				template.Generate();
				template.SaveAs(fileName);

also the template is attached. 

thanks in advance
[STUDENT_LIST.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3578831/STUDENT_LIST.xlsx)

**Comment by b0bi79** [comment]
Did you manage to solve the problem?

**Comment by b0bi79** [comment]
Closed due to a long wait for an answer. If the issue is still relevant, reopen it.
