### ISSUE TITLE
Adding custom text into subtotals row

### ISSUE THREAD

**Issue by iRumba** [ClosedXML/ClosedXML.Report#108]
I want to write custom text inside subtotals (and totals) row. How can i do? After generation my cells with custom text become empty. I don't want to add some string by parameter `TotalLabel`, i want use custom string in any empty sell inside subtotals row.

This is image what i want.

![image](https://user-images.githubusercontent.com/12796309/65952238-c76db480-e46b-11e9-9841-077831fa9f34.png)

**Comment by b0bi79** [comment]
It would be more understandable if you showed most of the table. In this example, I understood a little.

**Comment by iRumba** [comment]
It is abstract example. 
"Subtotal by" is constant text. I found solution for this - use `&=Subtotal by`. But this string shows in grand total too. It is logical behavior, but it is not what i want.

"Group 1" - is name of group, that had got by `<<group>>` tag.

**Comment by b0bi79** [comment]
Try using conditional formatting to hide this line in grand total. In the examples you can find how to do this.

**Comment by iRumba** [comment]
Yeah, I used conditional value instead of formatting. 
I have setted TotalLabel and GrandLabel to empty string "".
So, cell with group name in grand row was empty. I thank. But it had space symbol. :)

I think grouping cell in subtotals and in grand total must have formatting label where `{0}` is group name. Or with named parameter instead of `{0}`. And grand total should not have total label string inside, but should have parameter for this string. Because current implementation useless for some languages, Russian for example. :)

**Comment by b0bi79** [comment]
You mean add `{0}` to TotalLabel?
What do you mean by "grand total should not have total label string inside, but should have parameter for this string"?

**Comment by iRumba** [comment]
`<<group TotalLabel="Total by: {0}">>`
OR
`<<group TotalLabel="Total by: {groupValue}">>`

What about grand totals

Label of grand totals is concatenation of GrandLabel and TotalLabel. More generic will
`<<group GrandLabel="Grand total">>` 

> ...but should have parameter for this string
means
`<<group GrandLabel="Grand {totalLabel}">>`  
but it is useless

**Comment by b0bi79** [comment]
https://github.com/ClosedXML/ClosedXML.Report/blob/develop/tests/Templates/GroupTagTests_FormulasInGroupRow.xlsx
This example does the same thing, but using group row formulas. Why don’t you want to use this approach?

**Comment by iRumba** [comment]
Because it does not simple for understanding. Templates - for users or data specialists, not for developers.

Also, a think that grouping must be tag for range with parameter for group property accessor. When i want to delete column with grouping item, i have to shift my data accessors to right regarding column titles.

**Comment by b0bi79** [comment]
Give an example of how you see it.

**Comment by b0bi79** [comment]
Closed due to a long lack of response.
