### ISSUE TITLE
How can I separate subtotals and totals properties?

### ISSUE THREAD

**Issue by iRumba** [ClosedXML/ClosedXML.Report#109]
I have columns a, b, c, d, e

I need show in subtotals column b, but in totals I need show b, c, d, e. How can I do it?

**Comment by b0bi79** [comment]
Grouping in ClosedXML.Report works similar to the SUBTOTAL function in Excel. Using the `<<group>>` tag, this result cannot be achieved. You can do this through the Master-Detail report. https://closedxml.github.io/ClosedXML.Report/docs/en/Nested-ranges_-Master-detail-reports

**Comment by iRumba** [comment]
It means that i must restructure my report data. But i don't want :(

In report row i have several nested entities

```
class ReportRow
{
  public Entity1 Entity1 {get;set;}
  public Entity2 Entity2 {get;set;}
  //etc.
}
```

I want to get data with relationship one-to-one between entities and start filters. Detail filters can set customer. Also customer can set grouping. It will impossible if my report struct will

```
class ReportRow
{
  public Entity1Group Entity1 {get;set;}
}

class Entity1Group
{
  public IEnumerable<Entity2> RelatedEntities { get; set; }
}
```

**Comment by b0bi79** [comment]
Possible solutions:
- use conditional formatting to hide unnecessary data;
- perform post-processing of the report and delete unnecessary data;
- make a contribution to the development of ClosedXML.Report by adding the feature you need.

**Comment by Pankraty** [comment]
* let ClosedXML.Report generate subtotals and put totals manually below the table

![image](https://user-images.githubusercontent.com/19576939/66181238-16d8fe00-e681-11e9-9484-e7aa7d29e779.png)

![image](https://user-images.githubusercontent.com/19576939/66181278-3a03ad80-e681-11e9-9c0a-e9af16f352a1.png)
