### ISSUE TITLE
onlyvalues tag with parameters

### ISSUE THREAD

**Issue by iRumba** [ClosedXML/ClosedXML.Report#110]
I have formula `&=SomeFormula(B5)`. I need change B5 to value (because B5 has tag `<<delete>>` and B5 become A5). But i need save formula.

**Comment by b0bi79** [comment]
You can add a hidden column (width 0) and write `=B5<<onlyvalues>>` in this column, and refer to the hidden column in the formula.

**Comment by iRumba** [comment]
Thanks! It is good solution!
