### ISSUE TITLE
How can I add to report end-to-end numbering?

### ISSUE THREAD

**Issue by iRumba** [ClosedXML/ClosedXML.Report#112]
I has grouping and ordering, setted by template. How can i add end-to-end numbering inside groups? Autofilters must be ignored.

![image](https://user-images.githubusercontent.com/12796309/66099590-9d360700-e5d1-11e9-8ad0-977c01bf8a80.png)

**Comment by b0bi79** [comment]
There is a solution here.
https://github.com/ClosedXML/ClosedXML.Report/issues/62
