### ISSUE TITLE
How can i use range with excluding subtotals in my totals?

### ISSUE THREAD

**Issue by iRumba** [ClosedXML/ClosedXML.Report#113]
I need to have grand totals and grand totals with ignoring autofilters. So i want use native excel sum for ranges of groups. How can I do it?

**Comment by b0bi79** [comment]
I do not quite understand what you need to do. See the example of [Groups with Captions](https://closedxml.github.io/ClosedXML.Report/docs/en/Examples#groups-with-captions), maybe this will help.
To better understand, give me the Excel file that you should get and your data classes.

**Comment by iRumba** [comment]
Look at this
![image](https://user-images.githubusercontent.com/12796309/66107082-9dda9780-e5e9-11e9-9cc7-c99e60272867.png)

When I apply autofilter with exclude "1" in last column, subtotal result decrease by 1 (became 8). It is normal behavior. But in grands i want show result with excluded rows and also without excluded rows. So i need use `sum()`. And i want use it in template. But i don't know how.

**Comment by b0bi79** [comment]
As I understand it, this topic duplicates the following https://github.com/ClosedXML/ClosedXML.Report/issues/114. I will close it

**Comment by iRumba** [comment]
Not really. I need 2 rows of grand totals. The first can be templated or native that sensetive to autofilters. But second must include hidden by autofilters cells to aggregation (sum() for example).

So, when I use native `subtotal()` formula with range, included value cell and total cell, this range become range from first row to last row. And `subtotal()` exclude other values from cells with `subtotal()` from aggregation. 

![image](https://user-images.githubusercontent.com/12796309/66176004-2eff4c00-e686-11e9-84d7-c297c90a34d9.png)

This formula is created manually

![image](https://user-images.githubusercontent.com/12796309/66176037-5bb36380-e686-11e9-8346-34db1975ee7a.png)

If i manually use `sum()` instead of `subtotal()` with same range i have result with subtotals. Without filters result will sum*2. Ok, i used `sum()/2` :) But after apliyng autofilters subtotals exclude values from calculation and guess that result of `sum(range)` is sum*2 becomes wrong.

**Comment by Pankraty** [comment]
Add a hidden column to your template where you output 1 for each data row. In group totals it will not have any value. Then `SUMPRODUCT` will do the trick:
![image](https://user-images.githubusercontent.com/19576939/66180305-92d14700-e67d-11e9-9796-01f36dc7f95f.png)

After a filter applied:
![image](https://user-images.githubusercontent.com/19576939/66180313-9a90eb80-e67d-11e9-82a0-700e5aeaa72c.png)

**Comment by Pankraty** [comment]
`=SUMIFS(F4:F10,B4:B10,"")` also fits (column B is, on the opposite, empty for data rows and non-empty for totals)
