### ISSUE TITLE
Dynamic templates

### ISSUE THREAD

**Issue by iRumba** [ClosedXML/ClosedXML.Report#115]
Are there ways to create dynamic template, when template includes headers, place for table general settings and footers?

There is report constructor where user can select columns and filters for report. Sure, I can use ClosedXml for xlsx file creation, but the constructor doesn't contains information about headers, footers and styles (for example table titles style). So using of ClosedXml without template is mean that we must change code and rebuild application for changing style of report.

**Comment by Pankraty** [comment]
1. Create an XLSX template with headers, footers, and styles. For example, you can predefine named regions, like, `COLUMN_HEADER`, `DATA_CELL`, etc.
2. Generate the dynamic template with ClosedXML by copying stylized cells from the first template to desired positions
3. Generate a report using ClosedXML.Report and the second template.
