### ISSUE TITLE
How to insert data into temptale from System.DataTable?

### ISSUE THREAD

**Issue by GeroIN21** [ClosedXML/ClosedXML.Report#118]
I loading data from db into DataTable, and trying to insert a data like this:
```c#
DataTable dt = new Reporter().GetData();
template.AddVariable("item", dt.AsEnumerable());
```

But, when the generated file is running, I see the following error in the table cells:
> Unknown identifier 'EnumerableRowCollection'

Tag in cell - {{item.UserID}}

**Comment by b0bi79** [comment]
Read this article [Flat-tables](https://closedxml.github.io/ClosedXML.Report/docs/ru/Flat-tables) please. Pay attention to what named regions should be.
As well you can add a DataTable without casting it to Enumerable:
```
template.AddVariable("item", dt);
```

**Comment by b0bi79** [comment]
Closed due to statute of limitations.
