### ISSUE TITLE
Can i add Validation to cells when create XLTemplate ?

### ISSUE THREAD

**Issue by nht1610** [ClosedXML/ClosedXML.Report#119]
Hi all
First, Thank you for your product. My english is not good.
[ImportExcel.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3701855/ImportExcel.xlsx)

This is my excel template , it work perfect before i create validation on Column F ( Gender ).

No fault was return but generate excel file is empty. This is my excel file after generate:
[ImportExcel123.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3701863/ImportExcel123.xlsx)

I tried to add validation on one row but it not work, no validation appear, although generate correctly.This is my excel file when validation one row
[ImportExcel_validation_one_row.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3701923/ImportExcel_validation_one_row.xlsx)
Thank you for reading and helping me, BestRegard !

**Comment by b0bi79** [comment]
Do you mean user input data validation?
![image](https://user-images.githubusercontent.com/1150085/66419778-5b5ff300-ea0d-11e9-94be-41159505cfe4.png)

**Comment by nht1610** [comment]
> Do you mean user input data validation?
> ![image](https://user-images.githubusercontent.com/1150085/66419778-5b5ff300-ea0d-11e9-94be-41159505cfe4.png)

Thank you for reply me.

Yes i mean user input data validation? it not work

**Comment by b0bi79** [comment]
Look at this issue #130
In the next version I plan to implement the Validation tag

**Comment by b0bi79** [comment]
Although now I think that it is better to implement this by copying the validation data assigned in the template.
