### ISSUE TITLE
Delete row dynamically

### ISSUE THREAD

**Issue by aamato80** [ClosedXML/ClosedXML.Report#120]
How is possible to delete a row based on his value calculated inside closed.xml report expression?
For example.
{{item.IsToDelete}} ???

Many thanks

**Comment by b0bi79** [comment]
Sorry, there is no such function. You can add such functionality to your project yourself. An example can be found here https://github.com/ClosedXML/ClosedXML.Report/issues/130#issuecomment-612430514
