### ISSUE TITLE
How to Repeater a collection ?

### ISSUE THREAD

**Issue by andysheu77** [ClosedXML/ClosedXML.Report#121]
```
myCollection = new List<myClass>();
...
var template = new XLTemplate(file);
template.AddVariable(myCollection);
template.Generate();
```
---
how to setting named the range in my template excel ?

**Comment by b0bi79** [comment]
Hi @andysheu77. Read here please https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

**Comment by andysheu77** [comment]
yes!i read that.and try.
as documents ,but  i want repeater custs   , not a single cust .
or i need put my collection in a class ? like
`class UpClass
{  public List<myClass> MyCollection{ get; set;} }
`
then named my range to "MyCollection" ?

**Comment by b0bi79** [comment]
what you mean "i want repeater custs"?

**Comment by Pankraty** [comment]
@andysheu77 

1. Attach your template
2. Provide code you use for generating a report
3. Attach the result you get
4. Attach a sample file with the result you _want_ to get

With this, it will be much easier for us to help you.

**Comment by andysheu77** [comment]
@Pankraty 
thank you! i was try out and success.
i put collection in a class , my data not master details, i only want print details,like Word Labels function.
