### ISSUE TITLE
Documentation is VERY poor and needs clarification

### ISSUE THREAD

**Issue by davija** [ClosedXML/ClosedXML.Report#122]
There is very little in the way of good documentation beyond simple tasks.

The example templates are nice, but it should also show the code that was used along with it to generate the target output.

**Comment by b0bi79** [comment]
If you have any difficulties, then I will try to help you. You can ask a question.

ClosedXML.Report is also an open, free product that develops on altruism. You can contribute to the project and improve the documentation.
