### ISSUE TITLE
How can I add charts/graphs in excel template?

### ISSUE THREAD

**Issue by Skanda-Kumar** [ClosedXML/ClosedXML.Report#123]
I want a chart/graph to be loaded along with data in excel report

**Comment by b0bi79** [comment]
ClosedXML.Report does not yet support the processing of charts. After generating the report, you can add the chart yourself using ClosedXML api.

**Comment by igitur** [comment]
> ClosedXML.Report does not yet support the processing of charts. After generating the report, you can add the chart yourself using ClosedXML api.

ClosedXML itself also has no support for charts.

**Comment by b0bi79** [comment]
@Skanda-Kumar Sorry, but then you cannot do it now

**Comment by Skanda-Kumar** [comment]
Ok thanks, for a quick reply...

**Comment by igitur** [comment]
My solution is to create an Excel template with the chart already included. Then use ClosedXML.Report to update the data source (don't touch the chart directly).

**Comment by Skanda-Kumar** [comment]
Ok will try that!

**Comment by Skanda-Kumar** [comment]
can you help me out with "Then use ClosedXML.Report to update the data source (don't touch the chart directly)."?

**Comment by igitur** [comment]
A chart refers to data on the spreadsheet itself. Actual cells with values. You can use ClosedXML.Report or just ClosedXML to update those values.
