### ISSUE TITLE
Very minor English corrections for Quick-start

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#124]
In case you are interested, some very minor corrections for the English Quick-start

https://closedxml.github.io/ClosedXML.Report/docs/en/Quick-start

from "files of Excel"
to "Excel files"

from "AutoFilter, Pivot tables to"
to "AutoFilter, and Pivot tables to"

from "Propagation conditional formatting"
to "Propagation of conditional formatting"

**Comment by Pankraty** [comment]
Thanks! Any help is always welcome.

**Comment by Pankraty** [comment]
Fixed.
