### ISSUE TITLE
Very minor corrections for English Simple-template

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#125]
https://closedxml.github.io/ClosedXML.Report/docs/en/Simple-template

from "in Russian version"
to "in the Russian version"

from "but escaped formula"
to "but the escaped formula"

from "formatted by any known way"
to "formatted in any known way"

from "Take a simple example:"
to "Here is a simple example:"
or "To take a simple example:"

**Comment by Pankraty** [comment]
Thanks again! Fixed.
