### ISSUE TITLE
Help request for making a simple table

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#126]
I am having trouble making a simple table from a simple list.

I made a template with a region named Bananas from A1 to G1.
In the cells I put things such as {{item.Color}} and {{item.Weight}}

In my code I made a list
` List<Banana> bananasIWant = someMethod();

My list has many bananas.

I execute this
```
 template.AddVariable("Bananas", bananasIWant);
 template.Generate();
 template.SaveAs("wherever");
```

It replaces the line with my first banana data, so I get a table with a single generated row.

How do I get it to generate all of them?

I tried doing a loop

```
foreach (var banana in bananasIWant)
{
  template.AddVariable(banana);
  template.Generate();
}
```
but then it throws an exception on the second banana with the error "An item with the same key has already been added."

In the sample, it seems to imply that it generates subrows for each order of the Customer based on the `List<Order> Orders` public property of the Customer.

So I also tried making a new class with a single public property which was my list of bananas, and named the property Bananas, but I still only get one row.

**Comment by Pankraty** [comment]
I think I had this problem too, but cannot check as am not near my PC at the moment. Try this, it may help:

template.AddVariable(new { Bananas = bananasIWant }) ;

We'll investigate how to make it work with plain collections.

**Comment by Pankraty** [comment]
Ah, and also, the named region Bananas in the template must have at least two rows (e.g. A1:G2). Keep in mind that the first column and the last row of the range are considered "service".

**Comment by Zorgle** [comment]
Thank you: based on your comments above I discovered that it was the lack of a second row. And I see that the flat table documentation already explicitly says that two rows are required; I just didn't read it well enough.
