### ISSUE TITLE
Very minor changes for English pages Flat-tables

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#127]
As the others, these are very, very minor. The English pages are entirely fluent and comprehensible, but these are just to make them sound more perfect. 

I worked my way down to the region section, for which I may post a suggested change after I get my code working.

https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

From "with the same name as variable."
To "with the same name as the variable."

From "use built-in name"
To "use the built-in name"

In the range configuration list, they should all be singular (Range, Cell) or plural (Ranges, Cells); I think plural sounds a little more natural, so:

From "Range can only be rectangular"
To "Ranges can only be rectangular"

From "Range must not have gaps"
To "Ranges must not have gaps"

From "While building a document ClosedXML.Report"
To "While building a document, ClosedXML.Report"

From "determines a data sources by their name"
To "determines data sources by their name"

From "tables, range name is built using underscore"
To "tables, the range name is built using an underscore"

From "E.g. to output"
To "E.g., to output"
Or "For example, to output"

From "serve to configuration purposes"
To "serve configuration purposes"

From "treated the special way"
To "treated a special way"

**Comment by b0bi79** [comment]
Thanks. Fixed
