### ISSUE TITLE
More very, very minor changes for English Flat-tables

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#128]
https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

From "Each range specifying the vertical table must"
To "Each range specifying a vertical table must"

From "The leftmost column and the bottom row serve to configuration purposes and are treated the special way. After the report is built the service column is cleared, and the service row is deleted if it is empty."
To "The leftmost column and bottommost row serve to hold configuration information and are treated specially. After the report is built the service column is cleared, and the service row is deleted if it is empty."

From "When dealing with vertical tables CLosedXML.Report acts this way:"
To "When dealing with vertical tables, CLosedXML.Report performs the following actions:"

From "Pay attention that cells are added"
To "Note that cells are added"

From "That means, regions located"
To "This means that regions located"

From "data according to template"
To "data according to the template"

From "not contain any options it is deleted"
To "not contain any options then it is deleted"
(To make it easier to read)

From "the service row they are"
To "the service row then they are"
(To make it easier to read)

From "Take a look into example from the"
To "Look at the example from the"

From "see on the picture"
To "see in the picture"

From "On the picture below you see"
To "In the picture below you see"

From "strict requirements as vertical tables do."
to "strict requirements as vertical tables."
(It was fine as it was, but the "do" was unnecessary.)

From "The named range consisting of a single row (in other words, does not contain an options row) it is assumed to be a horizontal."
To "The named range consists of a single row (in other words, without an options row) and is assumed to be a horizontal table."

From "The horizontal one does not need to have a service column either."
To "A horizontal table does not need to have a service column either."

From "table definition put a special tag"
To "table definition, put a special tag"

**Comment by b0bi79** [comment]
Many thanks. Fixed
