### ISSUE TITLE
Minor fixes for English Sorting doc

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#129]
https://closedxml.github.io/ClosedXML.Report/docs/en/Sorting

From "in a service row of target columns."
To "in the target columns of the service row."

From "may choose the descending order"
To "may choose a descending order"

From "the data sorted in the descending"
To "the data sorted in descending"

From "Besides, you are able to specify the order different columns are sorted by adding the parameter"
To "You also may add additional columns to the sort by adding the parameter"

From "Sorting in ClosedXML.Report has a certain limitation:"
To "Sorting in ClosedXML.Report has this limitation:"

From "If this is not a option for you consider sorting"
To "If this is not possible for you, consider sorting"

**Comment by b0bi79** [comment]
@Zorgle Thank you for your contribution
