### ISSUE TITLE
Would it be possible to copy data validation with the cells when generating?

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#130]
Do you know if it would be feasible to copy data validation with the cells when generating the new cells?

By testing with Excel, I see that adding a simple yes/no validation rule produces this in the "sheet1.xml" file inside the document:

```
<dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="A1" xr:uid="{GGGG-guid-etc}"><formula1>"yes,no"</formula1></dataValidation></dataValidations>
```

This suggests, unfortunately I fear, that maybe validations hang at the sheet root and are connected to cells by whatever that "sqref" element is, which means they may not be found from the cell level at all.

I started looking at the source a little bit, and I think maybe the generation occurs in method RangeTemplateVerticalTable?

Wondering if you've looked at this at all?

**Comment by Zorgle** [comment]
I had another idea; I thought maybe I could attach the data validation to a columnar range, and that way it would hopefully expand to include the generated rows.

However, when I tried it, I get an error because ClosedXML.Reports finds my columnar range and complaints that it is not a property on the collection.

Is there a way to name a range so ClosedXML.Reports will ignore it and not fail because it is not a property name?

I tried to trace by examination where this would be in the code, and I think it would be somewhere in or called by RangeTemplate.Parse, but I haven't figured out beyond that.

**Comment by Zorgle** [comment]
Would it work to revise RangeTemplate.GetInnerRanges
from
```
.Where(rr => rr != nr)
```
to
```
.Where(rr => rr != nr && !rr.Name.StartsWith("_"))
```
?

I tried to test, ran into the version incompatibilites:

I had to port my code back to ClosedXML 0.92 because the current NuGet version of ClosedXML.Report is linked against 0.92

The current github source for ClosedXMLReport doesn't seem to compile against any release version of ClosedXML

**Comment by b0bi79** [comment]
Current ClosedXML.Report was built for ClosedXML 0.95.0-beta1

**Comment by Zorgle** [comment]
Yes, I saw that, and I was unable to run it with my code b/c my code is using release versions of ClosedXML.

Do you know if:

Would it work to revise RangeTemplate.GetInnerRanges
from

.Where(rr => rr != nr)

to

.Where(rr => rr != nr && !rr.Name.StartsWith("_"))

?

to allow the use of ranges starting with _ inside the template--so it will ignore them and not fail with an exception, because it only wants to allow properties?

**Comment by Zorgle** [comment]
My suggestion above didn't seem to work.
I also tried excluding subranges beginning with _ from the assignment to _subranges in Parse, but that didn't work either.

**Comment by b0bi79** [comment]
Over the weekend, I'll looks what can be done. I don’t have enough time now.

**Comment by Zorgle** [comment]
I figured out how to compile my code against a prerelease of ClosedXML, and then use a cloned copy of this repo, so I got down to just having to actually figure out a way to make this work, but, I couldn't figure out how to make either of my ideas above actually work, even trying them out in code.

**Comment by Zorgle** [comment]
I couldn't figure out how to do data validation in template rows. If anyone knows a way to do it, I'd be very interested.

**Comment by b0bi79** [comment]
I started developing ValidationTag, on the weekend I will give it to you

**Comment by b0bi79** [comment]
Try, please this code.

Add class `ValidationTag` to your project

```
/*
Validation Options
====================================================
PARAMS                  
====================================================
AllowedValues       AnyValue(default)|WholeNumber|Decimal|Date|Time|TextLength|List|Custom
Operator            EqualTo(default)|NotEqualTo|GreaterThan|LessThan|EqualOrGreaterThan|EqualOrLessThan|Between|NotBetween
Value               String|Range
MinValue            String|Range
MaxValue            String|Range
ProcessBlanks       on|off(default)
HideErrorMessage    on|off(default)
ErrorTitle          String
ErrorMessage        String
HideInputMessage    on|off(default)
InputTitle          String
InputMessage        String
HideDropdown        on|off(default)
================================================

EXAMPLES
================================================
<<Validation AllowedValues="WholeNumber" Operator="Between" MinValue="=D11" MaxValue="100" ProcessBlanks>>
<<Validation List="=D11:D18">>
================================================
*/

using ClosedXML.Excel;
using ClosedXML.Report.Excel;
using ClosedXML.Report.Utils;

namespace ClosedXML.Report.Options
{
    public class ValidationTag: OptionTag
    {
        public override void Execute(ProcessingContext context)
        {
            var xlCell = Cell.GetXlCell(context.Range);
            var ws = Range.Worksheet;

            if (HasParameter("List"))
            {
                var listStr = GetParameter("List");
                var listRange = ws.ParseRange(listStr);
                if (listRange != null)
                    xlCell.DataValidation.List(listRange);
                else
                    xlCell.DataValidation.List(listStr);
            }

            xlCell.DataValidation.AllowedValues = GetParameter("AllowedValues").AsEnum(XLAllowedValues.AnyValue);
            xlCell.DataValidation.Operator = GetParameter("Operator").AsEnum(XLOperator.EqualTo);
            xlCell.DataValidation.Value = GetParameter("Value");
            xlCell.DataValidation.MinValue = GetParameter("MinValue");
            xlCell.DataValidation.MaxValue = GetParameter("MaxValue");
            xlCell.DataValidation.IgnoreBlanks = !GetParameter("ProcessBlanks").AsBool();
            xlCell.DataValidation.ShowErrorMessage = !GetParameter("HideErrorMessage").AsBool();
            xlCell.DataValidation.ErrorTitle = GetParameter("ErrorTitle");
            xlCell.DataValidation.ErrorMessage = GetParameter("ErrorMessage");
            xlCell.DataValidation.ShowInputMessage = !GetParameter("HideInputMessage").AsBool();
            xlCell.DataValidation.InputTitle = GetParameter("InputTitle");
            xlCell.DataValidation.InputMessage = GetParameter("InputMessage");
            xlCell.DataValidation.InCellDropdown = !GetParameter("HideDropdown").AsBool();
        }
    }
}

```

Register `ValidationTag` to `TagsRegister`
```
            TagsRegister.Add<ValidationTag>("Validation", 0);
```

**Comment by b0bi79** [comment]
TODO Now I think that it is better to implement this by copying the validation data assigned in the template.

**Comment by b0bi79** [comment]
Done
