### ISSUE TITLE
Would it be possible to generate a new NuGet package against ClosedXML 0.94?

### ISSUE THREAD

**Issue by Zorgle** [ClosedXML/ClosedXML.Report#131]
Would it be possible to generate a new ClosedXML.Reports NuGet package against ClosedXML 0.94?

I ask because 0.92 (against which the existing package is linked) and 0.94 have different behavior with respect to whether cell.ValueCached or cell.CachedValue are populated.

**Comment by Zorgle** [comment]
Just compiled and ran the source against 0.95.beta, so it looks like this would be feasible?

**Comment by Zorgle** [comment]
But it appears that it won't compile against 0.94.2, the latest stable?
> No overload for method 'Relative' takes 2 arguments

**Comment by b0bi79** [comment]
We did not have the version that we would build for 0.94. If I have time, then in the evening I will try to do downgrade 0.95 to 0.94. Upgrade 0.92 to 0.94 will be very difficult.

**Comment by b0bi79** [comment]
If you add this method to the XlExtensions class, you can build it. But ClosedXML version 0.94 is not optimized and has some errors, so some tests fail, and some work for a very long time. For these reasons, I cannot build a Nuget package.
```
/// <summary>
/// Get range relative to another range.
/// </summary>
/// <param name="range">range</param>
/// <param name="baseRange">Coordinate system. Coordinates are calculated relative to this range.</param>
/// <param name="targetBase"></param>
public static IXLRange Relative(this IXLRangeBase range, IXLRangeBase baseRange, IXLRangeBase targetBase)
{
    var xlRange = targetBase.Worksheet.Range(
        range.RangeAddress.FirstAddress.RowNumber - baseRange.RangeAddress.FirstAddress.RowNumber + 1,
        range.RangeAddress.FirstAddress.ColumnNumber - baseRange.RangeAddress.FirstAddress.ColumnNumber + 1,
        range.RangeAddress.LastAddress.RowNumber - baseRange.RangeAddress.FirstAddress.RowNumber + 1,
        range.RangeAddress.LastAddress.ColumnNumber - baseRange.RangeAddress.FirstAddress.ColumnNumber + 1);

    var type = targetBase.GetType();
    var method = type.GetMethod("Range", new[] { typeof(IXLRangeAddress) });
    return (IXLRange)method.Invoke(targetBase, new object[] { xlRange.RangeAddress });
    //return targetBase.Range(xlRange.RangeAddress);
}
```

**Comment by Zorgle** [comment]
Oh, so the next real release version is held up until ClosedXML itself goes to a release version, right?

Thanks for explaining, and giving me the code to try.

**Comment by b0bi79** [comment]
Yes that's right. Waiting for release 0.95

**Comment by igitur** [comment]
I plan to release v0.95 soon. Sorry @b0bi79, I promised to include support for pivot formats, but I haven't been able to do that yet.

**Comment by b0bi79** [comment]
@igitur It's good. I will prepare.

**Comment by UriHendler** [comment]
ClosedXML v0.95.2 has been released.

Is it possible to upgrade yet?

I found a bug with merged cells (Excel complained the worksheet was invalid when I opened it). When I compiled ClosedXML.Report against ClosedXML v0.95.2, the problem went away.

**Comment by b0bi79** [comment]
version 0.2.0 has been released
