### ISSUE TITLE
How to use a list as an variable

### ISSUE THREAD

**Issue by bugproof** [ClosedXML/ClosedXML.Report#137]
I think the example in the README is wrong because it shows a screenshot with a list of orders but there isn't any orders variable in the code. 

```cs
class TestItem
{
    public string Name { get; set; }
}
```

![image](https://user-images.githubusercontent.com/3116731/81261109-b73e3900-903b-11ea-91f1-5c9f5a4169f4.png)

```cs
const string outputFile = @".\report.xlsx";
var template = new XLTemplate(@".\template.xlsx");

var testList = new List<TestItem>()
{
    new TestItem{ Name="Foo"},
    new TestItem{Name="Bar"}
 };

template.AddVariable("item", testList.ToArray());
template.Generate();

template.SaveAs(outputFile);
```

**Comment by b0bi79** [comment]
Your template does not meet the requirements. Collections should be wrapped in named regions. See the documentation for details.
https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

**Comment by bugproof** [comment]
Thanks! That did the trick.
