### ISSUE TITLE
Can we group on multiple columns

### ISSUE THREAD

**Issue by yoazerty** [ClosedXML/ClosedXML.Report#138]
Hello guys,

First of all, thank you very much for you work!
I already made different tests but I cannot achieve grouping on multiple columns. I would like to have something like this?
![ClosedXML](https://user-images.githubusercontent.com/48250044/81274339-6f75dc80-9050-11ea-9292-5c3606ec2b2b.png)

Is it possible to group on multiple columns like this?

Thanks for reply,
Regards.

**Comment by b0bi79** [comment]
You can achieve grouping in two ways. First, use the group tag. Second, using the Master-Detail approach. Look what is more convenient for you.

https://closedxml.github.io/ClosedXML.Report/docs/en/Grouping

https://closedxml.github.io/ClosedXML.Report/docs/en/Nested-ranges_-Master-detail-reports

**Comment by yoazerty** [comment]
ok thank you for you quick reply, I'll dig into this direction

**Comment by yoazerty** [comment]
Could you send me the code behind the report Subtotals in Master-Detail Reports please? because I'm facing an error : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

And I just not understand why.

Thank you,
Regards.

**Comment by b0bi79** [comment]
https://github.com/ClosedXML/ClosedXML.Report/blob/9bfd63058b2d377cf0cb2c36b5b7a2b8a985111c/tests/ClosedXML.Report.Tests/SubrangesTests.cs#L18
