### ISSUE TITLE
Grouping bug

### ISSUE THREAD

**Issue by Platonenkov** [ClosedXML/ClosedXML.Report#139]
I Trying to group the data by column.
But for some reason the grouping takes the wrong line and breaks down the data not belonging to it, including the grouping line
[need.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4598813/need.xlsx)
[result.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4598814/result.xlsx)
[Template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4598816/Template.xlsx)

**Comment by b0bi79** [comment]
I guess this offset might be due to the Filters table over the Faults. Need to check.

**Comment by b0bi79** [comment]
I checked your template on the latest version 0.2.0 and could not reproduce the problem. Try to repeat your test on 0.2.0.

**Comment by Platonenkov** [comment]
Yes in 0.2.0 it work, but not have group lines
![image](https://user-images.githubusercontent.com/44946855/81799014-63d75980-9519-11ea-8a52-7e7e31a236ed.png)
![image](https://user-images.githubusercontent.com/44946855/81799069-7baedd80-9519-11ea-92da-ef72785bd714.png)

and if I have 2 table AutoFilter will set only in first
![image](https://user-images.githubusercontent.com/44946855/81799202-abf67c00-9519-11ea-8bdf-0f7a64b6e5d9.png)
![image](https://user-images.githubusercontent.com/44946855/81799219-b3b62080-9519-11ea-8ec6-9c3ff0651869.png)

[Standard template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4621209/Standard.template.xlsx)
[result.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4621212/result.xlsx)

**Comment by Platonenkov** [comment]
and it work after update ClosedXML to 0.95.2
![image](https://user-images.githubusercontent.com/44946855/81800100-fb897780-951a-11ea-8606-2e5ec7a9358f.png)

**Comment by Platonenkov** [comment]
but, when i close gruop it close header...
![image](https://user-images.githubusercontent.com/44946855/81800227-2d024300-951b-11ea-9d87-586d89175ce8.png)

**Comment by Platonenkov** [comment]
I see that grouping starts 1 line higher than it should.

**Comment by b0bi79** [comment]
Could you send your last template? And how many rows do you have in the second table?

**Comment by Platonenkov** [comment]
Total rows in the second table?
from 0 to ∞
[Standard template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4628587/Standard.template.xlsx)

In the current template, if I collapse lines - the group header closes

And if the table has 0 rows and template have <<RowsFit>>I have critical error.

**Comment by b0bi79** [comment]
The problem is not reproducible
