### ISSUE TITLE
Signed version of nuget package references to non-signed ClosedXML.

### ISSUE THREAD

**Issue by NicholasNoise** [ClosedXML/ClosedXML.Report#145]
https://www.nuget.org/packages/ClosedXML.Report.Signed/0.2.0-beta1
https://www.nuget.org/packages/ClosedXML.Report.Signed/0.2.0

Beta version references ClosedXML.Signed, but release version does not.

Was it done intentionally?

**Comment by b0bi79** [comment]
You sent a link to the release. https://www.nuget.org/packages/ClosedXML.Report.Signed/0.2.0

What do you want to say?

**Comment by Pankraty** [comment]
@b0bi79 , Nicholas is right - in 0.2.0 Signed we reference ClosedXML while it should be ClosedXML.Signed (like in 0.2.0-beta and before). Though I don't understand how this happened considering the build is done automatically

**Comment by NicholasNoise** [comment]
Will you republish package with correct dependency?

**Comment by NicholasNoise** [comment]
@Pankraty, any news?

**Comment by b0bi79** [comment]
@NicholasNoise Sorry, I made a mistake when publishing. Unfortunately, Nuget does not allow to update the old version, can only publish a new one. Now I don't want to publish the new version without any changes. Over the weekend, I will try to make some bug fixes and publish a new version. Now, you can download the compiled signed binaries here https://github.com/ClosedXML/ClosedXML.Report/releases/download/0.2.0/ClosedXML.Report.Signed.zip

**Comment by NicholasNoise** [comment]
Yeah, a new publish will be perfectly fine, 0.2.1-beta-what-ever :)
I use signed nuget package as a dependency of private one, so binaries does not make a difference here.
Patiently waiting for upcoming patch release.

**Comment by NicholasNoise** [comment]
@b0bi79 @Pankraty 
Any updates?

**Comment by b0bi79** [comment]
Today I plan to release 2.2.0
