### ISSUE TITLE
template.Generate() very slowly

### ISSUE THREAD

**Issue by daivph** [ClosedXML/ClosedXML.Report#146]
My Code

`public IActionResult ReportExcel()
{
	var filePathExit = @"\app\ExcelTemplate.xlsx";

	string strPath = _env.WebRootPath + filePathExit;

       //Data only 1 record

       //This line very slow, about 9 seconds or more

	var data = _service.GetAllData();

	MemoryStream stream = new MemoryStream();   
       
	using (var template = new XLTemplate(strPath))
	{
		template.AddVariable("items", data);
		template.Generate();
		template.SaveAs(stream);
	}
	stream.Position = 0;
	string ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
	string fileName = "Test.xlsx";
	return File(stream, ContentType, fileName);
}`

Sometime this function not response in line (template.Generate();)

**Comment by b0bi79** [comment]
>//This line very slow, about 9 seconds or more
>var data = _service.GetAllData();

Receiving data takes 9 seconds? Send your model code and template.

**Comment by daivph** [comment]
@b0bi79 Sory. This line very slow and sometime  not response in line
template.Generate();
[Test.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4692642/Test.xlsx)

**Comment by b0bi79** [comment]
1. Your template is wrong. Add an options column to the top of the table. Read the [Docs](https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables#vertical-tables) 
>Each range specifying a vertical table must have at least two columns and two rows. 

2. Please provide a complete test, how can I repeat your problem. My tests work very fast.

**Comment by daivph** [comment]
@b0bi79 Many thanks. Amazing :)
This is updated template. It's work.
[Test_Template_Updated.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4699198/Test_Template_Updated.xlsx)
