### ISSUE TITLE
Bump System.Linq.Dynamic.Core from 1.0.9 to 1.1.1 (or latest) 

### ISSUE THREAD

**Issue by JohannesStoll1984** [ClosedXML/ClosedXML.Report#149]
Hi guys,
can you please bump the version for the dependency "System.Linq.Dynamic.Core" from 1.0.9 to 1.1.1 (latest) in NuGet package. Although the package description says that it works with version 1.0.9 and above, it actually does not (see screenshots)!

`System.Linq.Dynamic.Core (>= 1.0.9)`

<img width="269" alt="01" src="https://user-images.githubusercontent.com/62992607/83139729-1ba96100-a0ed-11ea-9db0-a8708a7b6871.png">

<img width="356" alt="02" src="https://user-images.githubusercontent.com/62992607/83139734-1e0bbb00-a0ed-11ea-8e30-6c603814122d.png">

<img width="832" alt="04" src="https://user-images.githubusercontent.com/62992607/83140824-f9184780-a0ee-11ea-9ee7-9eb911382bb2.png">

There is  a runtime error claiming version 1.0.9 hard, although it should work with versions above 1.0.9 as well.

Can you check and correct if necessary? We do not have the option of downgrading to 1.0.9, so we depend on that change. Thanks.

**Comment by b0bi79** [comment]
Duplicate #148

**Comment by JohannesStoll1984** [comment]
Thanks Alexey for linking to #148!
