### ISSUE TITLE
<<group>> + <<sum>> kill below tables

### ISSUE THREAD

**Issue by NikitaEgorov** [ClosedXML/ClosedXML.Report#152]
When I add `<<sum>>` to `<<group>>` tables that stay below grouped become corrupted

[GroupTagTests_MergeLabels2.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4712044/GroupTagTests_MergeLabels2.xlsx)

![image](https://user-images.githubusercontent.com/10349650/83423791-27ba5900-a434-11ea-88a1-c72baad1ff5d.png)

![image](https://user-images.githubusercontent.com/10349650/83423838-3739a200-a434-11ea-83bb-d74a11c904c4.png)

**Comment by NikitaEgorov** [comment]
Additional issue
if i put table before "group" table when Excel group not working

![image](https://user-images.githubusercontent.com/10349650/83426428-c72d1b00-a437-11ea-945d-20cb22e670e6.png)

**Comment by b0bi79** [comment]
Fixed with #160
