### ISSUE TITLE
Formulas Not caliculated until open is opened

### ISSUE THREAD

**Issue by NikitaEgorov** [ClosedXML/ClosedXML.Report#153]
Same issue https://github.com/ClosedXML/ClosedXML/issues/653

Workaround

```
var memoryStream = new MemoryStream();
template.Workbook.SaveAs(memoryStream, true, true);
memoryStream.Seek(0, SeekOrigin.Begin);
```

**Comment by b0bi79** [comment]
Sorry, the question is not related to ClosedXML.Report. Ask it on ClosedXML.

**Comment by NikitaEgorov** [comment]
ClosedXML.Report can't give me a chance to recalculate formulas

**Comment by b0bi79** [comment]
Does the same work without ClosedXML?

**Comment by NikitaEgorov** [comment]
Let me explain
When I use ClosedXML.Report in my main asp.net application. The user downloads the report and sees empty cells with formulas.
I found the same thing in ClosedXML that corrects passing additional parameters to the SaveAs method
But ClosedXML.Report does not have overload SaveAs with Boolean evaluateFormulae parameter
And in this issue I ask: could you add overload SaveAs to ClosedXML.Report

**Comment by b0bi79** [comment]
Oh thanks. Sorry, I misunderstood you.

I will add overloading to XLTemplate.SaveAs.

To get around this issue in the current version, you can call the save as follows.

```c#
template.Workbook.SaveAs("file.xlsx", true, true);
```

**Comment by raeesgillani** [comment]
Hi, normal formulas calculate correctly when using the overload "true, true" on the SaveAs method. However, it does not seem to work for array formulas for example {=MAX(....)}. It seems to only calculate once the file is fully open and in editing mode. Please advise.

**Comment by igitur** [comment]
ClosedXML doesn't support array formulas yet.

**Comment by raeesgillani** [comment]
But the array formula calculates correctly when I open the file?

**Comment by igitur** [comment]
> But the array formula calculates correctly when I open the file?

Yes, Excel does that automatically if the stored file is missing values for some cells.

**Comment by raeesgillani** [comment]
But you've provided using array formulas here as an example?: https://github.com/ClosedXML/ClosedXML/wiki/Using-Formulas
