### ISSUE TITLE
Put custom values into Group Row

### ISSUE THREAD

**Issue by NikitaEgorov** [ClosedXML/ClosedXML.Report#155]
I have table grouped by first column `<<group MergeLabels placetocolumn=2 DisableOutline>> <<DisableGrandTotal>><<Delete>>`

And  i need put custom values into group row (green cells)
![image](https://user-images.githubusercontent.com/10349650/83634538-61fa3680-a5ab-11ea-95c3-c8f13b291234.png)

How can I do it?

**Comment by b0bi79** [comment]
An example [Formulas In Group Row](https://closedxml.github.io/ClosedXML.Report/docs/ru/Examples#формулы-в-строке-группы) shows how to do this.
