### ISSUE TITLE
Update System.Linq.Dynamic.Core to v1.1.2

### ISSUE THREAD

**Issue by NikitaEgorov** [ClosedXML/ClosedXML.Report#158]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/releases/tag/v1.1.2

**Comment by b0bi79** [comment]
For ClosedXML.Report there is no need to chase the latest versions of dependencies. If you need to have the latest version in your project, then you can update System.Linq.Dynamic.Core to version 1.1.2. There will be no compatibility issues.
