### ISSUE TITLE
Tag ColsFit isn't working for worksheet column

### ISSUE THREAD

**Issue by makeProjectGreatAgain** [ClosedXML/ClosedXML.Report#172]
# Tag ColsFit isn't working for worksheet column
wiki says:
> Tag ColsFit
Causes automatic alignment of column widths by value in the cells of the columns of ... the entire sheet column (if specified on the first line of the sheet)

## template:
![image](https://user-images.githubusercontent.com/24358142/85143560-93812c00-b252-11ea-9932-328e0f6ae5e1.png)
[BugTagColsFitForWorksheetCol.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4805129/BugTagColsFitForWorksheetCol.xlsx)

## result:
![image](https://user-images.githubusercontent.com/24358142/85143721-c62b2480-b252-11ea-94c5-c2715383b04c.png)
[result.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4805133/result.xlsx)

## expected result:
![image](https://user-images.githubusercontent.com/24358142/85143798-e65ae380-b252-11ea-8abc-b27a4c0cb0b2.png)
[expectedResult.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4805140/expectedResult.xlsx)

## Code to reproduce problem:
```
using ClosedXML.Report;
using System.Diagnostics;

namespace BugClosedXmlTagColsFit
{
    class Program
    {
        static void Main(string[] args)
        {
            Report();
        }

        public static void Report()
        {
            const string outputFile = @".\Output\result.xlsx";
            var template = new XLTemplate(@".\Templates\BugTagColsFitForWorksheetCol.xlsx");
            //template.AddVariable(cust);
            template.Generate();         
            template.SaveAs(outputFile);

            //Show report
            Process.Start(new ProcessStartInfo(outputFile) { UseShellExecute = true });
        }
    }
}
```
___
I also want to ask 
> Causes automatic alignment of column widths by value in the cells of the columns of the entire report (if specified for the report)

How I can specify it for the report or range?

**Comment by b0bi79** [comment]
> How I can specify it for the report or range?

whole workbook - if (cellAddr == "A1")
whole worksheet - if (cellAddr == "A2")
worksheet column - if (cellRow == 1)
whole range - if (IsSpecialRangeCell(xlCell)) // leftmost cell of a range options row
range column - if (IsSpecialRangeRow(xlCell)) // any cell of a range options row
