### ISSUE TITLE
Row below the nested range goes left

### ISSUE THREAD

**Issue by makeProjectGreatAgain** [ClosedXML/ClosedXML.Report#174]
## template:
![Issue173](https://user-images.githubusercontent.com/24358142/86157170-ac6dc500-bb0f-11ea-8050-ea21f542eb2a.png)
[RowBelowTheNestedRangeGoesLeft.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4853519/RowBelowTheNestedRangeGoesLeft.xlsx)

## result:
![image](https://user-images.githubusercontent.com/24358142/86157701-767d1080-bb10-11ea-9f59-1de6ef5369df.png)
[result.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4853536/result.xlsx)

## expected result:
![image](https://user-images.githubusercontent.com/24358142/86157996-d70c4d80-bb10-11ea-894d-24708ae28c95.png)
[expectedResult.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/4853546/expectedResult.xlsx)

## Code to reproduce the problem:
[repository with the code and the Excel template](https://github.com/makeProjectGreatAgain/ClosedXmlReportIssue173)

___
## upd:
Only one row goes left
![image](https://user-images.githubusercontent.com/24358142/86160538-90b8ed80-bb14-11ea-8092-d7f67d621cad.png)

**Comment by jpwLeeCombs** [comment]
I have the same issue, but was able to have it apply a bit more. The nested range goes left as the initial example does when both ranges share the "A" column for their config columns. However, having the nested column use "B" as its config column causes the issue within the generated rows in addition to the initial issue.

**Template:**
<img width="569" alt="ClosedXMLIssue" src="https://user-images.githubusercontent.com/66966630/93632783-eb4b4280-f9bb-11ea-9779-4ce738b72c01.png">

**Result:** (Both the total row (red) goes left, and nested rows (green), after the first row, go left)
<img width="571" alt="ClosedXMLIssue2" src="https://user-images.githubusercontent.com/66966630/93632781-eab2ac00-f9bb-11ea-8cb9-cafe81735c0d.png">

**Comment by b0bi79** [comment]
Fixed with #204
