### ISSUE TITLE
Change Cell Style using Variable

### ISSUE THREAD

**Issue by netcorefan** [ClosedXML/ClosedXML.Report#175]
Hi,

Is there ant way to dynamically change background color at the same time Generate() replace values?
Is it posible add some delegate/s to library to invoke for cell render with parameters (items, ....) in order to implement other change to cell after o before Library change value?

**Comment by b0bi79** [comment]
This can be done by adding a custom tag. I gave an example of custom tag here https://github.com/ClosedXML/ClosedXML.Report/issues/130#issuecomment-612430514

**Comment by Pankraty** [comment]
Or, you can use the power of conditional format. Visually, the results will be the same, but with conditional formats cell styles will reflect changes after the report is generated, if user modifies data manually. Sometimes this may be a preferable behavior.

**Comment by b0bi79** [comment]
> Or, you can use the power of conditional format. Visually, the results will be the same, but with conditional formats cell styles will reflect changes after the report is generated, if user modifies data manually. Sometimes this may be a preferable behavior.

@Pankraty I think that due to the changed behavior of the function of combining ranges for conditional formatting, ClosedXML does not combine colored conditional formats. At least I didn’t succeed, so I did not offer this option.
