### ISSUE TITLE
How to access nested dictionary members

### ISSUE THREAD

**Issue by dragana991** [ClosedXML/ClosedXML.Report#177]
Hi,

I have the following json string:

[
   {
      "ID":123,
      "Name":{
         "FirstName":"Jon",
         "LastName":"Snow"
      }
   },
   {
      "ID":321,
      "Name":{
         "FirstName":"Arya",
         "LastName":"Stark"
      }
   }
]

that is deserialized to List <<object>>{
    Dictionary<string,object>{{ID:123}, {Name: DIctionary<string,object> {FirstName : Jon, LastName : Snow}}}
   ...
}

Here is my code that defines workbook:
var wb = new XLWorkbook();
            var ws = wb.AddWorksheet("Sheet1");
            ws.Range("A2:C3").AddToNamed("Base");
            ws.Cell(1, 2).Value = "ID";
            ws.Cell(1, 3).Value = "Name";
            ws.Cell(2, 2).Value = "{{item.ID}}";
            ws.Cell(2, 3).Value = "{{item.Name.FirstName}}";

//template generating

 excelTemplate.AddVariable("Base", excelData); 
excelData is deserialized data.

After the template is generated, I got the excel with data structured as :

| ID   | Name |
|123  | Jon     |
|321  | Jon     |

So, name is always same as the name of the first item.

Why did this happen? How can I access the members of the nested dictionaries?

**Comment by b0bi79** [comment]
This seems to be a issue in System.Linq.Dynamic.Core. I created a ticket, we will wait for the new version https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/397

**Comment by dragana991** [comment]
Thank you.

**Comment by b0bi79** [comment]
Fixed with #207
