### ISSUE TITLE
Is there a way to access child collection in named range without adding an explicit variable?

### ISSUE THREAD

**Issue by AiratShaimuhamitov** [ClosedXML/ClosedXML.Report#182]
Hi,
I am trying to access child collection in named range declaration like I would do it with a simple cell using {{}} (but without braces):
<img width="250" alt="Снимок экрана 2020-08-14 в 16 17 24" src="https://user-images.githubusercontent.com/18355855/90254519-8dbb5780-de4b-11ea-9c3d-01845bcfdecc.png">
And what I am getting: 
<img width="350" alt="Снимок экрана 2020-08-14 в 16 20 31" src="https://user-images.githubusercontent.com/18355855/90254678-d115c600-de4b-11ea-86b7-52fcebbb99e0.png">

Is this behavior not supported? Or I am doing something wrong? It works fine if I define named range as "Workers" and add a variable - `AddVariable("Workers", company.Project.Workers);`

Here's my piece of code:
```csharp
class Company
{
    public Project Project { get; set; }
}

class Project
{
    public List<Worker> Workers { get; set; }
}

class Worker
{
    public string Name { get; set; }
}
```

```csharp
...
var company = new Company
{
    Project = new Project
    {
        Workers = new List<Worker>
        {
            new Worker { Name = "Ivan Ivanov" }
        }
    }
};

const string outputFile = @"report.xlsx";
var template = new XLTemplate("template.xlsx");
template.AddVariable(company);
template.Generate();
```

**Comment by Pankraty** [comment]
#181 addresses this exact issue. Try the artifacts from the PR build, it should work
https://ci.appveyor.com/project/ClosedXML/closedxml-report/builds/34424752/job/nb78ac7ook7vea2i/artifacts
https://ci.appveyor.com/project/ClosedXML/closedxml-report/builds/34424752/job/s411hsal035ebmty/artifacts

**Comment by AiratShaimuhamitov** [comment]
@Pankraty thank you!
