### ISSUE TITLE
How to leave cell empty if object is null?

### ISSUE THREAD

**Issue by kamil-szprych** [ClosedXML/ClosedXML.Report#184]
In my range in excel i had something like this:
![image](https://user-images.githubusercontent.com/51128962/91277186-c7ad2780-e782-11ea-8159-de4f6ae7f478.png)

But when `ProductionPrice` is null it throws error. 
Then i changed it to something like this: 
`{{item.ProductionPrice == null ? 0 : item.ProductionPrice.Value}}` 
It worked, but i want to have cells empty and not filled with `0`. When i change `0` to `""` it doesn't work because `ProductionPrice.Value` is decimal, so it says that null cannot be decimal.

Is there any way to make it work like i want without changing decimal to nullable decimal?

**Comment by b0bi79** [comment]
Try it
`{{item.ProductionPrice == null ? null : (decimal?)item.ProductionPrice.Value}}`

**Comment by b0bi79** [comment]
Then you can solve this issue through formatting using Excel or through conditional formatting.

**Comment by kamil-szprych** [comment]
i can't because 0 can be a valid value sometimes, i can't just clear all cells conaining 0

**Comment by b0bi79** [comment]
Then return result as a string:
`{{item.ProductionPrice == null ? "" : item.ProductionPrice.Value.ToString()}}`

**Comment by Pankraty** [comment]
I'm far from my PC and can't check how I solved similar issue, but I used something like `&=IF({{item.Value}} = NULL, "", {{item.Value}}) <<OnlyValues>>`
Excel formula IF does not care about data types (unlike C# ternary operator) and <<onlyValues>> tag (or is it only_values?) will get rid of formulas in resulted file leaving just plain values. Hope this will help
