### ISSUE TITLE
The grouplabel cannot meet expectations

### ISSUE THREAD

**Issue by shouyong** [ClosedXML/ClosedXML.Report#189]
https://github.com/ClosedXML/ClosedXML.Report/blob/1d4831db8748d2cdde9454122017430b7884fa54/tests/ClosedXML.Report.Tests/XlTemplateTests.cs#L78

for this test add group label, will err.

template like this:
![image](https://user-images.githubusercontent.com/37922155/99478952-497eac80-2990-11eb-8ef1-6ed4d01ee68b.png)

expected：
![image](https://user-images.githubusercontent.com/37922155/99478709-d8d79000-298f-11eb-98f3-92d4485efb2d.png)

result:
![image](https://user-images.githubusercontent.com/37922155/99479628-7bdcd980-2991-11eb-90a8-3c862aa9245c.png)

**Comment by b0bi79** [comment]
The problem is not reproducible
