### ISSUE TITLE
How can I output a list into a object?

### ISSUE THREAD

**Issue by ngockhainguyen97** [ClosedXML/ClosedXML.Report#191]
This is my class:
public class Sample
{
        public SampleModel SampleModel { get; set; }
}

public class SampleModel
{
        public List<SampleModel2> SampleModel2List { get; set; }
}

public class SampleModel2
{
        public string SampleModel2_1 { get; set; }
        public string SampleModel2_2 { get; set; }
}

How can i create a template to output SampleModel2List from Sample?

I'm using XLTemplate..AddVariable(Sample);

Thanks.

**Comment by b0bi79** [comment]
You need add list as variable
```c#
template.AddVariable('list', Sample.SampleModel2List);
```
And name the named range to which the table should be output `list`
