### ISSUE TITLE
Adding DynamicLinqType

### ISSUE THREAD

**Issue by cordasfilip** [ClosedXML/ClosedXML.Report#192]
Is it possible to add a custom DynamicLinqType extender in excel template? 
From what I can see you are using https://dynamic-linq.net/advanced-extending but I am unable to add a custom function.
Looks like it would be really useful and don't really see why this would not be supported.

**Comment by b0bi79** [comment]
Now I checked the work with DynamicLinqType in the template. Everything worked as expected. Can you describe your problem in more detail?

**Comment by cordasfilip** [comment]
> Now I checked the work with DynamicLinqType in the template. Everything worked as expected. Can you describe your problem in more detail?

Hmm that is strange could you post the sample code? And what version of .net did you test this?
I just copied the sample https://dynamic-linq.net/advanced-extending and tries using the IncrementMe function in the template({{item.SomeInt.IncrementMe()}}) and was getting method not found.

**Comment by b0bi79** [comment]
I added a class with a `DynamicLinqType` attribute
```c#
    [DynamicLinqType]
    public static class EvaluateUtils
    {
        public static int ParseAsInt(string value)
        {
            if (value == null)
            {
                return 0;
            }

            return int.Parse(value);
        }

        public static int IncrementMe(this int values)
        {
            return values + 1;
        }
    }
```

And in the template added `{{EvaluateUtils.ParseAsInt (Zip)}}`

**Comment by b0bi79** [comment]
Try to call it not as an extension method, but as a regular method of a static class.

**Comment by cordasfilip** [comment]
@b0bi79 Works on the regular method, but not extension method. Probably an issue with dynamic linq. Would be nice if extension methods worked because it's a good way to do pipes until you add the | pipe operator.

**Comment by b0bi79** [comment]
I think the version of DynamicLinq in use does not support extension methods. Need to update to the latest version.
