### ISSUE TITLE
issue with Simple Template address

### ISSUE THREAD

**Issue by qjohnchen** [ClosedXML/ClosedXML.Report#196]
Just got ClosedXML.Report today:
    ClosedXML.Report: v0.2.1.0
    ClosedXML: 0.95.0.0
    DocumentFormat.OpenXML: 2.7.2.0
    ExcelNumberFormat: 1.0.10.0
Using Visual Studio 2019 (target framework .Net 4.8)
MS Excel from Office 16.

I download simple template from https://closedxml.github.io/ClosedXML.Report/docs/en/Simple-template
Tried my code. 
            var cust = new Customer();
            cust.Company = "Micky Giant Inc";
            cust.Addr1 = "1234";
            cust.Addr2 = "Fifth";
            cust.City = "Anytown";
            cust.State = "IL";
            cust.Country = "USA";
            cust.Zip = "60606";
            cust.Phone = "312-456-7890";
            cust.Fax = "312-456-7899";
            cust.Contact = "Johnny Doe";

            template.AddVariable(cust);

            template.Generate();
            template.SaveAs(outputFile);

Looks great except the address. The result is =1234&" "&@Fifth 
I also tried a few different addresses and got various results (all bad).

Should I not worry about this because I am just at beginning of the whole ClosedXML.Report thing or it is a bug.

Thanks,

John

**Comment by b0bi79** [comment]
Thanks. This is the ugly formula in the template for this example. I'll fix it.
