### ISSUE TITLE
Is it possible to auto adjust row height?

### ISSUE THREAD

**Issue by vi3tkhi3m** [ClosedXML/ClosedXML.Report#197]
Is there a feature that allows rows to auto adjust height according to contents? I know that there's one for columns (<<ColsFit>>), but is there also one for rows? I can't seem to find this in the documents...

I can apply "Wrap Text" and "AutoFit Row Height" to the cell in Excel, but this will only work for the first row of the data. See image below:
![image](https://user-images.githubusercontent.com/37420560/109377766-48f48c80-7882-11eb-8b11-a212e677f354.png)

Template:
[template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6053829/template.xlsx)

**Comment by b0bi79** [comment]
Try use `RowsFit` tag.
If tag `RowsFit` found in the A1 cell, it apply to whole workbook. 
A2 - whole sheet. 
In the first column of the sheet - applied to all row cells.
In the first column of the range - applied to all range row cells.
Other cells - only this cell.
