### ISSUE TITLE
Two datatables one below the other

### ISSUE THREAD

**Issue by TakhirMamirov** [ClosedXML/ClosedXML.Report#198]
How shall I create and build the XLXS file so it would contain two different size datatables, one above the other. Right now the top one is populated fine, but the bottom one not and left as an original markup (tags). If I skip populating the top one, then the bottom one is build correctly.

**Comment by Pankraty** [comment]
@TakhirMamirov when defining a named range for the top table make is as wide (or wider) as the bottom one. This way, when the range will grow, it will move the bottom table as a whole, not screwing it.

**Comment by TakhirMamirov** [comment]
@Pankraty thanks, that worked! But the only things is left... Imagine, that the top dataset is just a one column list, say, 1*10. Right to that there is a static list, which displays some helper information. So what happens now is that when dynamic top dataset is populated with data, it then forces to right helper static list to extend with duplicated values in the middle. As the dynamic left list grows, seems that it adds rows that forces values from the right list to be duplicated. How can I freeze the right helper list then?

P.S. The helper list looks like that:

Omfattningskoder*
--
T = Trafik
D = Delkasko
V = Vagnskada
H = Hyrbil
A = Assistans
S = Självriskeliminering
C = Care
P = Pluspaket
E = Pluspaket Extra
B = Återlämnandeförsäkring

and after XLSX file is built it becomes:


Omfattningskoder*
--
T = Trafik
D = Delkasko
V = Vagnskada
H = Hyrbil
**A = Assistans
A = Assistans
A = Assistans**
S = Självriskeliminering
C = Care
P = Pluspaket
E = Pluspaket Extra
B = Återlämnandeförsäkring

**Comment by Pankraty** [comment]
Yeah, this layout cannot be correctly implemented in ClosedXML.Report. You should either move the helper block to be fully above the top table, or fill it "manually" as post-processing for the built report.

**Comment by TakhirMamirov** [comment]
@Pankraty can you please navigate me to the documentation where I can find example for that post-processing? At the moment here is my code:

```
using (Stream templateStream = assembly.GetManifestResourceStream(templateResourceName))
            {
                var template = new XLTemplate(templateStream);

                template.AddVariable(report);
                template.Generate();

                var stream = new MemoryStream();

                template.SaveAs(stream);
                stream.Position = 0;
                return stream;
            }
```

**Comment by Pankraty** [comment]
Notice that `template` has a property `Workbook` - this is an ordinary ClosedXML workbook and you are free to do with it whatever you need - add data, conditional formats, stylize it, etc. Be the power of ClosedXML with you (https://github.com/ClosedXML/ClosedXML/wiki) :-)

**Comment by b0bi79** [comment]
It cannot be fixed due to the peculiarities of constructing tables in ClosedXML.Report
