### ISSUE TITLE
Dictionary as data source

### ISSUE THREAD

**Issue by AntoniTodryk** [ClosedXML/ClosedXML.Report#2]
Hi,

Is it possible to pass dictionary to template as a variable for usecase when data structure is being specified only in runtime?
so not to create class:
`
class Person {
    string FirstName { get; set; }
    string LastName { get; set; }
}

...

template.AddVariable(personObj)
`
but
`
var data = SomeDataRetrievingMethod();
template.AddVariable(data);
`

Thank you

**Comment by AntoniTodryk** [comment]
Yeah, but how can we treat complex data?
For instance:
```
new Dictionary<string, object>() {
    {"Property1", "Value1"},
    {"Property2", new Dictionary<string, object>() {
        {"FirstName", "John"},
        {"LastName", "Doe"}
    }
}
```

**Comment by b0bi79** [comment]
OK. In the near future I will add this functionality.

**Comment by Fox2726** [comment]
Could you give us a sapmle?
We try to write "dic" in templates. but it's not work.
Thanks.

**Comment by b0bi79** [comment]
Unfortunately, after switching to the new parsing library "System.Linq.Dynamic.Core" this feature became unavailable. But I have an idea how to return this functionality, only time is missing. In the next version I will implement it.

**Comment by kitzler-walli** [comment]
Is that feature already available again? I'm currently struggling with Dictionaries or ExpandoObjects and both don't work for me currently.
