### ISSUE TITLE
Translate wiki documentation

### ISSUE THREAD

**Issue by Pankraty** [ClosedXML/ClosedXML.Report#20]
As agreed, I'm going to translate documentation into English. Create an issue just to not forget.

**Comment by Pankraty** [comment]
`Flat-tables` translated

**Comment by Pankraty** [comment]
> каждая область в иерархии вложенности рассматривается как единой целое за вычетом всех вложенных в нее областей, которые были описаны в предыдущих главах.

Я не понял, что тут имеется в виду.

**Comment by Pankraty** [comment]
`Nested Ranges: Master-detail Report` translated

**Comment by b0bi79** [comment]
Перевёл ты правильно. Другими словами можно сказать так: каждая область (минус внутренние диапазоны) считается единым целым.

**Comment by b0bi79** [comment]
Добавлена статья Сортировка на русском языке.

**Comment by Pankraty** [comment]
* Sorting translated
* Examples translated
* Theme changed
* New logo added
