### ISSUE TITLE
How to create correct hyperlinks using ClosedXML.Report?

### ISSUE THREAD

**Issue by Finardin** [ClosedXML/ClosedXML.Report#208]
Hi there. 
I need to create the hyperlink in one of my xls-temnplate's cells. Thanks to wiki i found how to do it using ClosedXML constructor (https://github.com/ClosedXML/ClosedXML/wiki/Using-Hyperlinks). but this is not what I need. 

I tried to send excel formula as a value of parameter (thomething like this: `$"=HYPERLINK(\"{PassportURL}\";\"Open\")"`) and it almost works, but Excel shows this value like a usual text. And it becames a real hyperlink only after I do mouse double-click on target cell and then press Enter (that is cell loose focus). 

Is there some correct ways to create normal hyperlinks in template's cells using ClosedXML.Report? 

Thank you in advance!

**Comment by Finardin** [comment]
according to this: https://closedxml.github.io/ClosedXML.Report/docs/en/Simple-template 
I also tried to insert the formula into target cell: `&=HYPERLINK("{{item.SampleAddress}}";"Open")`
But it doesn't work too, Excel generate an error while opening a file and then remove the value of target cell.

**Comment by Finardin** [comment]
Anyone?

**Comment by b0bi79** [comment]
Sorry, I have not seen the emails from github, they ended up in spam. I will try to help you in the near future.

**Comment by b0bi79** [comment]
Now the processing of hyperlinks only created through the form for creating hyperlinks has been implemented. Hyperlinks created using formulas will be supported in future releases.
To solve the problem, create a hyperlink via Insert -> Hyperlink. As address type: `{{item.SampleAddress}}`

![image](https://user-images.githubusercontent.com/1150085/127277628-644088ad-f723-47e7-a1a9-d978ab2f9fcd.png)

**Comment by b0bi79** [comment]
To add a hyperlink it is recommended to use a formula like this: `&=HYPERLINK("mailto:{{item.Email}}","{{item.Email}}")`
In your formula, instead of `;` it should be `,`
