### ISSUE TITLE
Single quote before value bug/arrays with different types of values

### ISSUE THREAD

**Issue by efimov90** [ClosedXML/ClosedXML.Report#210]
In cell adds ' symbol before value.
I add this tree as variable: Report->ReportRow->Days[] (string)

I also tried to make Days object[] instead of string[], but then i get System.ArgumentException: 'Object of type 'System.String' cannot be converted to type 'System.Int32'.'

I have different types of values in my report, so i can't just use numeric types.

**Comment by efimov90** [comment]
It works like this because of FormulaEveluator->Eval (Initial commit:69, :97)

If you change Eval function to this:
` 
       private object Eval(string expression, Parameter[] pars)
        {
            var parameters = pars.Select(p => p.ParameterExpression).ToArray();
            var lambda = DynamicExpressionParser.ParseLambda(parameters, typeof(object), expression, _variables).Compile();
            return lambda?.DynamicInvoke(pars.Select(p => p.Value).ToArray());
        }
`

It will work, but there is no cache now and then i can use object[] for this.

**Comment by b0bi79** [comment]
I already had problems with expression caching. It will be necessary to somehow solve this, but it is not yet clear how.

**Comment by b0bi79** [comment]
Fixed with #214

**Comment by efimov90** [comment]
awesome! thanks, hope package will be updated soon
