### ISSUE TITLE
Generate() taking long time.  

### ISSUE THREAD

**Issue by joy-sensato** [ClosedXML/ClosedXML.Report#211]
Following is my code. 

var template = new XLTemplate(Server.MapPath("~/Stores/CreditBillPayment/CREDIT_BILL_PAYMENT_TEMPLATE.xlsx"));

  fileName = Server.MapPath("~/ReportOutput/" + fileName);

  template.AddVariable("PAYMENT_DTL", oDt);

  template.AddVariable("LOGIN_NAME", oDt.Rows[0]["LOGIN_NAME"]);
  template.AddVariable("PRINT_TIME", oDt.Rows[0]["PRINT_TIME"]);

  template.Generate();  --- taking to much time to generate. datatable row count < 2500 as of now.  attaching my excel template.

version info

![image](https://user-images.githubusercontent.com/54879962/124873817-93caa180-dfe4-11eb-9be9-e9958bb14708.png)

[CREDIT_BILL_PAYMENT_TEMPLATE.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6782075/CREDIT_BILL_PAYMENT_TEMPLATE.xlsx)

**Comment by b0bi79** [comment]
I found the `<<ColsFit>>` tag for a table range to work for a very long time. If you move all the `<<ColsFit>>` tags to the first row, then the test will run in 6 seconds.
![image](https://user-images.githubusercontent.com/1150085/129542349-b662b010-adfa-4e2d-88fb-2ad8e567b63c.png)
