### ISSUE TITLE
Exception when using lambda expressions with the entire list of items

### ISSUE THREAD

**Issue by ThunderCls** [ClosedXML/ClosedXML.Report#212]
Hey guys, first and foremost I want to take a minute to appreciate the work you guys are doing with this amazing library, it is awesome! Lately I've been trying to use lambda expressions on the "items" variable inside a table and I've been getting an exception with a simple Count(). This is my expression:
```
{{items.Count(i => i.Id == 1)}}
```
And it crashes with the following message:
```
System.InvalidCastException: 'Unable to cast object of type 'System.Linq.Expressions.DynamicExpression1' to type 'System.Linq.Expressions.ParameterExpression'.'
```
And this is my template:
![image](https://user-images.githubusercontent.com/13303069/125002757-a6b09680-e023-11eb-81dd-3cdd7b7e1f31.png)

Am I doing something wrong here or this is an issue with the library?
Thanks!

**Comment by b0bi79** [comment]
Fixed with #215
