### ISSUE TITLE
Performance: Background Fill Issue

### ISSUE THREAD

**Issue by llotall** [ClosedXML/ClosedXML.Report#219]
Hello everyone.
I met with the problem that related with the filling of the background.

**ClosedXML.Report Version=0.2.0**

The goal report shold be seems like that:
![image](https://user-images.githubusercontent.com/18103301/125276231-a7457780-e318-11eb-8b5b-1f0cf1688e5d.png)

Around tables shouldn't be some borders.
For reach this result I filled background of an template to white color:
![image](https://user-images.githubusercontent.com/18103301/125276609-18852a80-e319-11eb-9873-f29907341940.png)

But after template generation ClosedXML automatically set borders (from first to the last excel column) that I deleted in template in each row that report generator interacted.

![image](https://user-images.githubusercontent.com/18103301/125280691-0659bb00-e31e-11eb-9a23-b6e71ba483f2.png)

I found workaround but this is decre4ase template generating performance:
1) I added selectors to the template 
2) by this selectors I create range and set background color to white
3) I clear the cells with selectors and get the desired result

BUT I cannot create a range until the last column of the worksheet and adjust the limit of the last column of the range for background padding, and as a result I populate the template to the part of the report that is not visible to the user.
And in seems like that 
![image](https://user-images.githubusercontent.com/18103301/125284344-01970600-e322-11eb-90db-82aba2f29f82.png)
![image](https://user-images.githubusercontent.com/18103301/125283457-1de67300-e321-11eb-817f-af7245a854ec.png)
And if user will scroll to right he will see borders.

It also decrease performance because for each rectangular area I have to create a range and fill it.

Can you fix this behavior of library. 
**If template has filled background of cells just don't touch styles and not add the borders that was not set in template.**

**Comment by b0bi79** [comment]
You can change this without filling Background, but simply turn off the grid: View -> Grid
![image](https://user-images.githubusercontent.com/1150085/125304854-97d52700-e336-11eb-9c2b-af73870c436b.png)

**Comment by llotall** [comment]
Yes, you are absolutely right, that's works.
I think will be not bad if you will add this information with example to documentation.
At least it wasn't obvious to me.

Thanks a lot)
