### ISSUE TITLE
Incorrect creating of range in one column

### ISSUE THREAD

**Issue by llotall** [ClosedXML/ClosedXML.Report#220]
**ClosedXML.Report Version=0.2.0**

If I trying create range in one column where last range row - last worksheet row
Range: A:1, A1048576 (last row)

But instead of this ClosedXML created range: (A1, A1)

This issue reproduces only for range with one column

**Comment by b0bi79** [comment]
Try repeat issue with 0.2.2 version. If the problem persists, please attach your template.
