### ISSUE TITLE
Combining Vertical and Horizontal areas

### ISSUE THREAD

**Issue by TarasBorovyk** [ClosedXML/ClosedXML.Report#223]
I have entity that has properties, which I want to display vertically.
Also, this entity contains property which is List, and I want to display it horizontally.
I'm using nested areas, but receiving errors.

Here is my template:
[template-output.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6848217/template-output.xlsx)
Code which I use:
[ClosedXML_POC.zip](https://github.com/ClosedXML/ClosedXML.Report/files/6848236/ClosedXML_POC.zip)
Or .txt:
[Code.txt](https://github.com/ClosedXML/ClosedXML.Report/files/6848272/Code.txt)

Exception I get:
![image](https://user-images.githubusercontent.com/33148330/126324145-873db158-7340-4593-a527-1d251248157e.png)

**Comment by b0bi79** [comment]
This issue has been fixed in version 0.2.2, which was released yesterday.
