### ISSUE TITLE
Is it possible to get a variable as table after generation?

### ISSUE THREAD

**Issue by CoenraadS** [ClosedXML/ClosedXML.Report#228]
```
template.AddVariable("MyData", IEnumerable<...>);
template.Generate();
```

Then I want to access this variable, but unsure how?
Something like
```
var table = template.GetVariable("MyData")
```

Basically I want to know the target cell of my data, as well as the bounds

**Comment by b0bi79** [comment]
Variable access is hidden inside the XLTemplate. If you need to get the value of your variables, you must keep them in your class.

**Comment by CoenraadS** [comment]
Is it then possible to set a pivot table to a string range? So I can pass variable name to `PivotTables.Add`

Basically I want to use template for table generation, but use code to add the pivot tables.
