### ISSUE TITLE
Time increasing with mapping one item in name manager for 2 worksheets

### ISSUE THREAD

**Issue by enverkrinickii** [ClosedXML/ClosedXML.Report#229]
I mapped my data to 2 worksheets and time increased in 100 times, for example report generation with mapping on one worksheet is 10 seconds, with mapping on 2 - about 3-5 minutes
Adding variable in c# code:
`xltTemplate.AddVariable(dataTable.TableName + "_Rows", dataTable.Rows);` (DataSet usage)
![image](https://user-images.githubusercontent.com/25920537/128862375-ed3e3aa5-e0f1-42a7-8ac0-0412a9081082.png)

**Comment by b0bi79** [comment]
To map the same data to multiple ranges, you must create ranges for each sheet separately.

![image](https://user-images.githubusercontent.com/1150085/130321396-360af7fd-05b1-4b0b-8e49-75a8a4988080.png)
