### ISSUE TITLE
Static pivot tables - (blank) row and column

### ISSUE THREAD

**Issue by BojicM** [ClosedXML/ClosedXML.Report#230]
Hi,

I am trying to create a report with a static pivot table. I could not find an example for this kind of template so I created my template file and selected the source range for the pivot table as it is described in the documentation. When the report is generated, the resulting pivot table data source range takes into account one additional row as the picture below shows:

![image](https://user-images.githubusercontent.com/47796757/129062400-cf0edcfc-79f4-45b2-a869-b019404d07d4.png)

As a consequence pivot table has one additional (blank) row and (blank) column (row 13 and column G in the example below):
![image](https://user-images.githubusercontent.com/47796757/129065528-314b4853-7e9e-4d36-bf71-b1bf1fa34ada.png)

Also, the formatting of the original pivot table in the template is not taken into account for headers of the pivot table in the generated file. 

Can you please tell me if I have missed something in the template and I am using it in the wrong way or this is an issue?

Here are the template and result files:
[Template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6969943/Template.xlsx)
[Result.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6969968/Result.xlsx)

Thanks in advance

**Comment by b0bi79** [comment]
Indeed, there is such a problem. Try removing any `<<sort>>` tags in the options line. Then no options row will be added to the resulting range. In the next version I will fix this issue.

**Comment by BojicM** [comment]
Workaround works fine, after removing <<sort>> tags there are no (blank) rows and columns.

Thanks a lot

**Comment by BojicM** [comment]
What about formatting for the static pivot table? Is there a way to keep the original formatting for the result pivot table?

**Comment by b0bi79** [comment]
ClosedXML still does not support pivot table formatting. You can raise this topic again so that the authors know that this is the desired feature.
https://github.com/ClosedXML/ClosedXML/pull/1250

**Comment by BojicM** [comment]
OK, thx

**Comment by CoenraadS** [comment]
I have the same issue, but not using any service row at all

**Comment by CoenraadS** [comment]
I have the same issue, but my tables are generated from code without any service rows. Look forwards to next release
