### ISSUE TITLE
Unexpected merging while using <<group MergeLabels=Merge2>> in nested groups？

### ISSUE THREAD

**Issue by Nycteus** [ClosedXML/ClosedXML.Report#235]
![image](https://user-images.githubusercontent.com/50039254/130179397-39adb011-6b0d-48a7-8a72-234f3dc49d86.png)

Hi, please see the screen capture for example.

**Comment by b0bi79** [comment]
In this case, I recommend using `Merge1` instead of `Merge2`.
`<<group MergeLabels Disablesubtotals>>`
It will be slightly different, but you will get the correct grouping.
I will fix it.
