### ISSUE TITLE
Three lists generation on one sheet hangs

### ISSUE THREAD

**Issue by kcabral817** [ClosedXML/ClosedXML.Report#246]
I have a sheet that has three lists.  When I generate Members by itself, with about 230 rows, it generates.  When I generate equipment and vehicles together, they both generate.  When I try and generate all three together or SetMembers with one other, the application hangs.  I have no idea why this is happening.  Process memory shoots up to 1.6 gig when the process runs after 5 min 40 seconds, after which I stopped it.  

Here is the sequence:
 `SetMembers();`  
`SetEquipmentItemInformation();` 
  `SetVehicleInformation();`
 
`private void SetMembers()`
`_template.AddVariable("CrewMemberList", members);`
` _template.Generate();  `

`private void SetEquipmentInformation()`
 `_template.AddVariable("CrewMemberList", members);`
` _template.Generate();`    <---- does not return; hangs;

`private void SetVehicleInformation()`    <---- never executes when all three methods are invoked.
`_template.AddVariable("VehicleList", vehicles);`  
`_template.Generate();`
[SpreadReportTemplate.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/7118820/SpreadReportTemplate.xlsx)

**Comment by b0bi79** [comment]
Could you please post the code of your models so that I can reproduce the problem?

**Comment by b0bi79** [comment]
The performance issue comes from a lot of merged ranges. I recommend that you redesign the template to minimize the merged ranges.
I will try to fix this performance issue in future releases.
