### ISSUE TITLE
Master Detail does not work

### ISSUE THREAD

**Issue by Hoschi1982** [ClosedXML/ClosedXML.Report#248]
Hy Guys,

i get the following message when I try to generate an excel file from a template:

'No property or field 'Addresses' exists in type 'List`1''

The code I used is the following:

`class Program
    {
        static void Main(string[] args)
        {
            GetReport();
        }

        protected static void GetReport()
        {
            const string outputFile = @".\Output\report.xlsx";
            var template = new XLTemplate(@".\Templates\PersonTemplate.xlsx");

            var context = GetContext();

            template.AddVariable(context);
            template.Generate();

            template.SaveAs(outputFile);

            //Show report
            Process.Start(new ProcessStartInfo(outputFile) { UseShellExecute = true });
        }

        private static Context GetContext()
        {
            var context = new Context();

            var persons = GetPersons(5);

            context.Persons = new List<Person>(persons);

            return context;
        }

        private static IEnumerable<Person> GetPersons(int count)
        {
            var values = Enumerable.Range(0, count + 1);

            foreach (var value in values)
            {
                var addresses = new List<Address>();
                for (int i = 0; i < 2; ++i)
                {
                    addresses.Add(new Address() { City = "N_" + value + "_" + i, Street = "S_" + value + "_" + i, HouseNumber = "H_" + value + "_" + i });
                }

                yield return new Person() { FirstName = "T" + value, LastName = "F" + value, Addresses = addresses };
            }
        }
    }

    public class Context
    {
        public List<Person> Persons { get; set; }
    }

    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public List<Address> Addresses { get; set; }
    }

    public class Address
    {
        public string City { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
    }`

The range is defined like that:

![grafik](https://user-images.githubusercontent.com/15252262/133305105-dcc7bdbc-5b39-4145-8f85-ab99fe61623c.png)

Template: [PersonTemplate.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/7164517/PersonTemplate.xlsx)

How can I solve the issue?

thanks a lot

**Comment by b0bi79** [comment]
Please, attach your template

**Comment by Hoschi1982** [comment]
The template is now attached. :) Thanks

**Comment by b0bi79** [comment]
Your code works fine with this template without modification. I just got this kind of result on ClosedXML.Report version 2.4:

![image](https://user-images.githubusercontent.com/1150085/133381579-c44358e5-3629-4ca9-ab28-2116311eead6.png)

**Comment by Hoschi1982** [comment]
Hy ... I see it.
I activated all exceptions in Visual Studio. So I saw the "green" internal exception.
When I step over it I can create the correct excel sheet.

Thanks for your help and I'm sorry for your wasted time.

**Comment by b0bi79** [comment]
It's ok. I was glad to help.
