### ISSUE TITLE
Problem with alignment, deletion and pictures

### ISSUE THREAD

**Issue by ajmmorrow** [ClosedXML/ClosedXML.Report#249]
I have a few problems in my template that I can not how to solve, so please help.
1) The picture is not transferred to the following cards (I attached it to a cell, but still does not copy it. Row 4 in a template).
2) Line alignment does not work in my case (I tried with RowsFit tag but failed).
3) How do I delete rows if the collection is empty?

[Payroll.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/7194469/Payroll.xlsx)

**Comment by b0bi79** [comment]
1. Sorry, but images cannot be copied. I will add this in future releases. For now, you can use the `<< Image >>` tag.
2. To apply the tag `<< RowsFit >>` to the entire book, it must be located in cell A1, to the current sheet A2.
3. There are currently no tools for such tasks. You can solve this by adding custom tag to ClosedXML.Report, which would remove empty rows. Also, this task can be solved by post-processing the generated report.

**Comment by ajmmorrow** [comment]
RowsFit does not work. Tried placing the tag in different cells. Including A1.  Can you tell me more about how to work with the `<<Image>>` tag. I could not find information about it in the documentation.

**Comment by b0bi79** [comment]
The easiest way to learn the Image tag is to look at [this test](
https://github.com/ClosedXML/ClosedXML.Report/blob/6be5de678867f5e5ce1efb24021dcfc373704b82/tests/ClosedXML.Report.Tests/GroupTagTests.cs#L29). The test works with [this template](https://github.com/ClosedXML/ClosedXML.Report/blob/develop/tests/Templates/tLists7_image.xlsx) and generates the [following a file](https://github.com/ClosedXML/ClosedXML.Report/blob/develop/tests/Gauges/tLists7_image.xlsx) at the output.

**Brief description of the tag.**
The image is passed through the `value` argument and can be of type Stream, Bitmap, or string. The `scale` parameter allows you to change the scale of the image. Width and Height lets you specify the dimensions of the image.

All this can be seen in the source code, everything is simple there. https://github.com/ClosedXML/ClosedXML.Report/blob/develop/ClosedXML.Report/Options/ImageTag.cs

**Comment by b0bi79** [comment]
> RowsFit does not work.
What does it look like? Attach an output file or screenshot.

**Comment by ajmmorrow** [comment]
[Payroll.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/7195845/Payroll.xlsx)

**Comment by ajmmorrow** [comment]
page "Зарплатные листы"

**Comment by ajmmorrow** [comment]
Here is the output file. The cell where the text is "Сборщик электрических..." is not aligned
![image](https://user-images.githubusercontent.com/61165776/134009673-44d67b65-79c5-455a-95e5-e05a5404ec62.png)

**Comment by b0bi79** [comment]
You must check the Word wrap box for this cell.
![image](https://user-images.githubusercontent.com/1150085/134019337-68a29d50-1cf6-4031-ab67-8cfd4a97851a.png)

**Comment by b0bi79** [comment]
As it turned out, ClosedXML does not take into account the WrapText attribute when calculating the line height, but only line breaks in the cell text.
As a quick fix, you can add NewLine to long lines of your data so that ClosedXML can change the line height.
I also advise you to support the ticket in ClosedXML issues https://github.com/ClosedXML/ClosedXML/issues/1702

**Comment by b0bi79** [comment]
I just thought that when setting the WrapText attribute, Excel should calculate the row height itself. Try removing RowsFit, it might help.

**Comment by ajmmorrow** [comment]
Thank you so much for your help!

**Comment by ajmmorrow** [comment]
Found the following solution (Only excel):
1) I set row.Cells("start cell : end cell").Style.Alignment.SetWrapText(true) for all cells used
2) I wrote a macro with the following text:
Range("A" & Row & ":N" & Row).EntireRow.AutoFit
3) Assigned it to run at document startup
