### ISSUE TITLE
Copying horizontal areas inscribed in a vertical area

### ISSUE THREAD

**Issue by ajmmorrow** [ClosedXML/ClosedXML.Report#250]
When you try to fill with data horizontal nested in vertical areas, the following error appears: "The sequence does not contain the corresponding element". I tried different options to overcome the problem, but they did not give any result. I realized that this happens when areas are moved. 
[Payroll2.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/7266776/Payroll2.xlsx) (Page: "Ведомость")

**Comment by b0bi79** [comment]
There is a test in the ClosedXML.Report similar to your template https://github.com/ClosedXML/ClosedXML.Report/blob/develop/tests/Templates/4.xlsx
To try to reproduce the problem, I made the test template even more similar to your template. Unfortunately, I could not repeat the problem.

Please attach the output file you receive. And also a test code that reproduces the described problem.

**Comment by ajmmorrow** [comment]
Found the cause of the problem. It turned out that one of the collections was equal to null. It would be good to make more detailed error texts to make it easier to find the source of the problem. Thanks for your help!

**Comment by ajmmorrow** [comment]
It would also be good to do the transfer of merged cells
