### ISSUE TITLE
Auto-fit not working on Linux containers

### ISSUE THREAD

**Issue by R4cOOn** [ClosedXML/ClosedXML.Report#259]
I'm running ClosedXML.Report in a Linux container (Alpine 3.14 image).

I had errors

> The type initializer for 'Gdip' threw an exception.

when running the template.

After going down the rabbit hole and installing `libgdiplus` I got these instead

> Font '?' cannot be found.

After some lengthy testing I isolated the issue: I used the directives `<<ColsFit>><<OnlyValues>>` to "auto-fit" the column sizes

I removed these and the report was generated without error.

It would have been helpful to have a more meaningful runtime error if these directives are not compatible with Linux.  
Or at least have some warnings in the documentation (that is quite helpful BTW, thanks for that).

Cheers.

**Comment by Pankraty** [comment]
This was not a ClosedXML.**Report** issue but rather a limitation of ClosedXML prior to 0.97. Starting ClosedXML.Report v 0.2.7 this should not be a problem anymore.
