### ISSUE TITLE
Несколько листов

### ISSUE THREAD

**Issue by DrBrown777** [ClosedXML/ClosedXML.Report#261]
Добрый день, подскажите а есть возможность генерации отчетов на нескольких листах?

**Comment by b0bi79** [comment]
Добрый день. 
Шаблон может иметь несколько листов, и каждый лист будет обработан.
Если имеется ввиду динамическая генерация листов, то пока это не реализовано. Есть в планах это сделать, но когда у меня найдётся для этого время сказать не могу.

**Comment by DrBrown777** [comment]
спасибо, за помощь, и забиблиотеку, уже реализовал что хотел, кусовой защитил! Работает все супер!
