### ISSUE TITLE
Are multiple sheets supported?

### ISSUE THREAD

**Issue by sfrozman** [ClosedXML/ClosedXML.Report#270]
I would like to have 5 years of data in one workbook, but have each year as a separate sheet.
I created a Sheet1 and Sheet2 in my Excel template.
I originally created named ranges which were "TeachingSummaries" with some nested ranges.
However with the two sheets, I renamed them as "One_TeachingSummaries" and "Two_TeachingSummaries" and tried to use them with variables.
template.AddVariable("One", currentYearSummary);
template.AddVariable("Two", secondYearSummary);

(currentYearSummary and secondYearSummary are List<TeachingSummary>)

The One_TeachingSummaries does seem to work with a scope of "Workbook" but not "Sheet1" and my Two_TeachingSummaries does not work with a scope of "Sheet2".

Is there a way to change my code, variable references or named ranges to accomodate two separate sheets?

**Comment by b0bi79** [comment]
Hello. Please attach your template.

**Comment by sfrozman** [comment]
Fortunately, after undoing my most recent changes to the Excel template to attach a version which I was describing above, my template is now working as I originally planned. It looks like I may have had a mistake in how the named ranges were defined or something.
So, I am closing this out.... it seems there is not an issue after all!
