### ISSUE TITLE
How to create a hyperlink to a bookmark in a word doc?

### ISSUE THREAD

**Issue by michaelgorman** [ClosedXML/ClosedXML.Report#271]
I pull this path from the excel cell \\someserver\ManualTestcases\Bond ABS Prepayment WAL Curve.doc#TC3 which points to a bookmark in a word doc. The path comes from the orginalstring property. Notice at the end of the path the #TC3 which is some bookmark within a word doc.  I can't figure out how to rewrite it back to the cell. I did look at the wiki https://github.com/ClosedXML/ClosedXML/wiki/Using-Hyperlinks but didnt find an example

      public static String GetHyperlinkValue(IXLCell cell)
      {
         if (cell != null && cell.HasHyperlink)
         {
            if (!String.IsNullOrEmpty(cell.Hyperlink.Tooltip))
               return cell.Hyperlink.Tooltip;
            if (!String.IsNullOrEmpty(cell.Hyperlink.ExternalAddress?.OriginalString))
               return cell.Hyperlink.ExternalAddress.OriginalString;
            if (!String.IsNullOrEmpty(cell.Hyperlink.InternalAddress))
               return cell.Hyperlink.InternalAddress;
         }
         return null;
      }

      public static void AddHyperlink(IXLWorksheet sheet, String path, String displayText)
      {
         if (!String.IsNullOrWhiteSpace(path))
         {
            Int32 pos = path.IndexOf("#");
            String file = (pos > 0 ? path.Substring(0, pos) : path);
            Object bookmark = (pos > 0 ? path.Substring(pos + 1) : Type.Missing);

            //file = System.Net.WebUtility.UrlDecode(file);
            var cell = sheet.Cell(TestCaseBase.TESTCASE_KEYWORDS, TestCaseRowBase.TESTCASE_DATA4);
            cell.Hyperlink = new XLHyperlink(path);
            cell.Hyperlink.Tooltip = path;
            cell.SetValue<String>(displayText);
         }
      }

**Comment by b0bi79** [comment]
I think you'd be better off creating a theme in the ClosedXML repository.
Look at this example, maybe it will help you:
```c#
ws.Cell(1, 1).Value = "Link to an email message";
ws.Cell(1, 1).Hyperlink.ExternalAddress = new Uri(@"mailto:SantaClaus@NorthPole.com?subject=Presents");
```

**Comment by michaelgorman** [comment]
@b0bi79 that didnt work but this does...

          var display = "Bookmark";
          var file = @"c:\temp\doc1.docx#TC3";
          cell.SetFormulaA1($"=HYPERLINK(\"{file}\", \"{display}\")");

Can you add this to the hyperlink wiki as an example or should i submit a new issue in the right place to have the wiki updated? I also see I submitted this issue in the wrong place.
