### ISSUE TITLE
Save option (UTF8 no BOM)

### ISSUE THREAD

**Issue by csm12s** [ClosedXML/ClosedXML.Report#282]
The default saved file encoding is UTF8 with BOM.

**Comment by Pankraty** [comment]
I am afraid I do not understand what is the nature of the problem. Can you provide any additional details, like, reproduction code, expected result, actual result, etc.?

**Comment by csm12s** [comment]
If you check other libs like Epplus or MiniExcel, the output file encoding is UTF8 no BOM.
I once want to read the file using Epplus, but it cannot read maybe because the file encoding.
