### ISSUE TITLE
The type initializer for 'Gdip' threw an exception

### ISSUE THREAD

**Issue by P9avel** [ClosedXML/ClosedXML.Report#283]
Hello, i am used worksheet.Columns().AdjustToContents() and get exeption in docker image. Now i am did
1. RUN apt-get update && apt-get install -y libgdiplus  in docker file
2. <ItemGroup>
		<RuntimeHostConfigurationOption Include="System.Drawing.EnableUnixSupport" Value="true" />
	</ItemGroup>    in running file

I think in next .Net version MS not will support System.Drawing. Possible can you to rewrite code for crossplatforming drawing dll?

**Comment by b0bi79** [comment]
Contact here [ClosedXML](https://github.com/ClosedXML/ClosedXML)
