### ISSUE TITLE
Accessing null children property throws an error (TargetInvocationException)

### ISSUE THREAD

**Issue by GersonDias** [ClosedXML/ClosedXML.Report#291]
item null complex objects results on TargetInvocationException when evaluating the lambda expression

Given an Array 
``` typescript
Array<{
  items: {
    name: string,
    foo?: {
       name: string
    }
}>
```

 if in the template we have ```{{item.foo.name}}``` and in some of the items foo property is null,
 this exception will be thrown.
  
created PR #290  to address this issue.

**Comment by b0bi79** [comment]
Closed with #290
