### ISSUE TITLE
Does not work in docker under linux

### ISSUE THREAD

**Issue by JeanRasin** [ClosedXML/ClosedXML.Report#293]
"ClassName": "System.TypeInitializationException",
            "Message": "The type initializer for 'Gdip' threw an exception.",
            "Data": null,
            "InnerException": {
                "ClassName": "System.PlatformNotSupportedException",
                "Message": "System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.",
                "Data": null,
                "InnerException": null,
                "HelpURL": null,
                "StackTraceString": "   at System.Drawing.LibraryResolver.EnsureRegistered()\n   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()\n   at System.Drawing.SafeNativeMethods.Gdip..cctor()",
                "RemoteStackTraceString": null,
                "RemoteStackIndex": 0,
                "ExceptionMethod": null,
                "HResult": -2146233031,
                "Source": "System.Drawing.Common",
                "WatsonBuckets": null
            },

Microsoft write https://learn.microsoft.com/ru-ru/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.

**Comment by Pankraty** [comment]
This was not a ClosedXML.**Report** issue but rather a limitation of ClosedXML prior to 0.97. Starting ClosedXML.Report v 0.2.7 this should not be a problem anymore.
