### ISSUE TITLE
using XLEventTracking.Disabled

### ISSUE THREAD

**Issue by lexo4kaa** [ClosedXML/ClosedXML.Report#296]
Hi! Can anyone tell me if we have an ability to use XLEventTracking.Disabled when creating a template, as was done in ClosedXML (new XLWorkbook(XLEventTracking.Disabled))? Thanks

**Comment by Pankraty** [comment]
`XLEventTracking.Disabled` has no effect starting from ClosedXML 0.93 where we removed internal events completely. Thus, there is no need to specify it for a template too.

**Comment by lexo4kaa** [comment]
Do we have other ways to speed up the SaveAs method? 
I have 4.500 rows and 1 Pivot table in my excel template. SaveAs works for more than 5 minutes.. 
For 200 rows and 1 pivot table everything is ok (some seconds), but in my situation (4500 rows, > 5 minutes) I can't wait that long

**Comment by Pankraty** [comment]
For this, you'd better open an issue in ClosedXML repository, with sufficient repro steps. No one can figure out what the problem is just by given numbers.

**Comment by lexo4kaa** [comment]
> 

I used classes from ClosedXML.Reports so I created a new issue here https://github.com/ClosedXML/ClosedXML.Report/issues/297
