### ISSUE TITLE
The SaveAs method takes too long

### ISSUE THREAD

**Issue by lexo4kaa** [ClosedXML/ClosedXML.Report#297]
**Template.SaveAs works for more than 5 minutes.. Is it possible to speed up this method?**

My steps:
1. Create template:

            FileStream TemplateStream = File.Open(templatePath, FileMode.Open);
            XLTemplate Template = new XLTemplate(TemplateStream);
3. Get data from context (≈25 columns, ≈4200 rows)
4. Add this data to template 

        Template.AddVariable(new { Data = dataList });
5. Call 

        Template.Generate()
6. Call

        public List<byte> GetTemplateBytes() {
            var ms = new MemoryStream();
            Template.SaveAs(ms);
            var workbookBytes = ms.ToArray();
            List<byte> byteList = new List<byte>();
            byteList.AddRange(workbookBytes);
            return byteList;
        }

**Comment by jahav** [comment]
There isn't a switch to speed up saving (unless the validate option is enabled in the `SaveOptions`, but it is off by default), There is has been work to improve memory performance (https://github.com/ClosedXML/ClosedXML/issues/1874), but from time perspective, it is still horrible (+it will take time to release improvements and propagate to ClosedXML.Report).

5 minutes is pretty excessive though, it should be roughly 2 minutes for 30k-50k rows (maybe pivot table makes it slower? Don't know).

**Comment by lexo4kaa** [comment]
I tried to do the same but without the pivot table. And it works very fast. How to speed up the creation of a pivot table?

**Comment by jahav** [comment]
File an issue over the [ClosedXML](https://github.com/ClosedXML/ClosedXML), though it might not get priority soon (pivot tables have worse problems than performance). Project has been on hiatus for a while and accumulated significant backlog, but it is being developed now.
