### ISSUE TITLE
Problem with versions

### ISSUE THREAD

**Issue by lexo4kaa** [ClosedXML/ClosedXML.Report#298]
I changed the ClosedXML version to 0.96/0.97 and the problem appeared 

**error CS0012: The type 'IXLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.95.0.0, Culture=neutral, PublicKeyToken=null'.**

(The problem is in this line: _Template = new XLTemplate(TemplateStream)_)

Is there support after version 0.95? If not, how can I change it?

**Comment by blahetal** [comment]
same here, I think this has to be updated to support closedxml v0.96+
in nuget, the closedxml version is not pinned - https://www.nuget.org/packages/ClosedXML.Report#dependencies-body-tab

**Comment by Pankraty** [comment]
Versions 0.2.7 and 0.2.8 (referencing ClosedXML 0.100 and 0.101, respectively) have been released lately. The version 0.2.9 (referencing 0.102) is on its way.
