### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by myo-min-tin** [ClosedXML/ClosedXML.Report#303]
I installed ClosedXML.Report (version 0.2.6) [Dependencies ClosedXML version is 0.97.0) from the NuGet and write a simple program.
When I run program, **it's OK**.
I also upgraded ClosedXML to the latest (version 0.100.3) and then when I run, I got this error message.

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void ClosedXML.Excel.IXLCell.set_Value(System.Object)'.
  Source=ClosedXML.Report
  StackTrace:
   at ClosedXML.Report.RangeInterpreter.ParseTags(IXLRange range, String rangeName)
   at ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
   at ClosedXML.Report.XLTemplate.Generate()
   at Program.<Main>$(String[] args) in D:\ConsoleApp\Program.cs:line 18

Here is the source.
```
var template = new XLTemplate(@"D:\Simple.xlsx");
var file = @"D:\Simple data.xlsx";
var cust = Customer.Default();

template.AddVariable(cust);
template.Generate();
template.SaveAs(file);
Process.Start(new ProcessStartInfo(file) { UseShellExecute = true });
```

**_I think, should be upgraded ClosedXML.Report to be working together with lasted update of ClosedXML._**

**Comment by HolgerKeller** [comment]
I get the same issue with ClosedXML.Report (version 0.2.6)  and ClosedXML version  0.100.3 .

**Comment by Maximiz** [comment]
same problem

**Comment by swekeshav** [comment]
I am getting the same issue :(

**Comment by d00lar** [comment]
same here ;/ will there be an update?

**Comment by myo-min-tin** [comment]
I cloned the ClosedXML.Report source and then made some fixes.
Now it's working with ClosedXML version 0.100.3 (no more errors and output results correctly) but I am not sure all features of ClosedXML.Report is working or not.

**Comment by swekeshav** [comment]
I understand that it will eat up some of your time but will it be possible for you to fork the Report repo, create a branch and a PR with your changes to your fork?

**Comment by Pankraty** [comment]
Or, simply create a PR to this repo and I will release a new version, compatible with the latest ClosedXML. I would really appreciate your help.

**Comment by myo-min-tin** [comment]
I did fork the Report repo, create a new branch, add & modify and pull request.

**Comment by vbondarev** [comment]
I cloned your branch and when I try to run `ClosedXML.Report.Tests` I get the error:

```
ClosedXML.Report.Tests.csproj: [NU1605] Warning As Error: Detected package downgrade: System.Linq.Dynamic.Core from 1.3.1 to 1.2.20. Reference the package directly from the project to select a different version. 
 ClosedXML.Report.Tests -> ClosedXML.Report -> System.Linq.Dynamic.Core (>= 1.3.1) 
 ClosedXML.Report.Tests -> System.Linq.Dynamic.Core (>= 1.2.20)
```

**Comment by vbondarev** [comment]
> I cloned the ClosedXML.Report source and then made some fixes. Now it's working with ClosedXML version 0.100.3 (no more errors and output results correctly) but I am not sure all features of ClosedXML.Report is working or not.

Yes, you are right )
I ran tests and got the next result

![image](https://user-images.githubusercontent.com/3437698/227303444-3107adbd-42be-4443-a52a-3a416123a877.png)

**Comment by vbondarev** [comment]
@mymintin I will create a new pull request based on your code. If you don't mind )

**Comment by borislizak** [comment]
Good day @vbondarev, are you planning to push the fix for it? We would like to upgrade to the latest ClosedXml version since there were a lot of performance fixes, but cannot due to this issue. It seems to be only working with ClosedXml 0.97.0 :(

**Comment by vbondarev** [comment]
> Good day @vbondarev, are you planning to push the fix for it? We would like to upgrade to the latest ClosedXml version since there were a lot of performance fixes, but cannot due to this issue. It seems to be only working with ClosedXml 0.97.0 :(

Hi. 
Yes, I plan to end this PR. But I have a lot of work. I will try to complete this task this week.

**Comment by spencerslade** [comment]
Just want to add another vote for this.  Thank you!!

**Comment by KIRANREDDY0228** [comment]
Hi @vbondarev ,  the above still getting. Please help us to fix above issue. please  try release new version by adding the fix

**Comment by KIRANREDDY0228** [comment]
Hi @vbondarev , Any update above issue .Please try to add fix and release new build.

**Comment by PopeyeZhong** [comment]
> I get the same issue with ClosedXML.Report (version 0.2.6) and ClosedXML version 0.100.3 .

This problem still exists today. 
The version I use is: ClosedXML.Report (version 0.2.6) and **ClosedXML version 0.102.0**

**Comment by Pankraty** [comment]
Versions 0.2.7 and 0.2.8 (referencing ClosedXML 0.100 and 0.101, respectively) have been released lately. The version 0.2.9 (referencing 0.102) is on its way.

**Comment by PopeyeZhong** [comment]
> Versions 0.2.7 and 0.2.8 (referencing ClosedXML 0.100 and 0.101, respectively) have been released lately. The version 0.2.9 (referencing 0.102) is on its way.

Thank you very much! ClosedXML.Report (**v0.2.8**) works well with ClosedXML(**v0.101**), but it doesn't match ClosedXML(_v0.102_).
