### ISSUE TITLE
Upgrade to closed xml 0.102.0 ?

### ISSUE THREAD

**Issue by fingers10** [ClosedXML/ClosedXML.Report#317]
Hey folks this is an awesome library and it would be great if we can upgrade the closed xml to latest version 0.102.0 to get all the benefits.

**Comment by jahav** [comment]
I plant to update the codebase after release of [ClosedXML 0.103](https://github.com/ClosedXML/ClosedXML/discussions/2112). It's not worth it, while major renovations are still underway.

**Comment by Pankraty** [comment]
I found it easier to make small gradual changes so I upgraded .Report to use ClosedXML 0.102. Hopefully, I'll be able to upgrade to 0.103 as well, once it is released.
