### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML.Report#32]
@Tobaloidee, can I ask you to redesign the green version of the ClosedXML logo? Our library is based on ClosedXML and is designed to generate reports in Excel using templates. If you find a little time, you could add ClosedXML.Report specific attributes to the original ClosedXML logo, for example {{}} or << >>. But it's not a matter of principle, I'm hope for your professional opinion.

Sorry for my English.

**Comment by Tobaloidee** [comment]
Sure Sir, i will edit it and show you here..I will just add the text " .Report " ? or i will put also the symbols to the logomark/favicon?

**Comment by Tobaloidee** [comment]
here are the options

![closedxmlreport-15](https://user-images.githubusercontent.com/36028424/41786671-c04dfb18-7678-11e8-9f38-9138c0f83e9b.png)

**Comment by b0bi79** [comment]
Great. It's even better than I thought. I prefer the second option (square << >>). @Pankraty, what do you say?

**Comment by Tobaloidee** [comment]
For me, its the 2nd on top right also

**Comment by b0bi79** [comment]
@Tobaloidee Yes, the upper right. I love it.
I also can offer you a postcard of my home town or a souvenir magnet. Write me an email (b0bi79 at gmail), to which address will you send the letter.

**Comment by Pankraty** [comment]
I actually like them all :) So hard to choose!

**Comment by Tobaloidee** [comment]
yes @b0bi79 i will email you earliest tomorrow..and also make a PR once the chosen logo was decided. :) sorry for making it hard to choose @Pankraty :)

**Comment by Pankraty** [comment]
After a thought, I would vote for a top-left example, but will, of course, accept the choice of @b0bi79 as the author of the library.

**Comment by b0bi79** [comment]
I also break my head which is better, on the one hand the right is more pleasing to the eye, but the left one more reflects the essence

**Comment by igitur** [comment]
I would just ask that it is easy to distinguish between the 2 libraries by looking at the logo.

**Comment by b0bi79** [comment]
Then it must be left upper.

**Comment by Tobaloidee** [comment]
Okay Sir, will a PR now with the upper left version

**Comment by Tobaloidee** [comment]
Here's the PR #33 Sir @b0bi79  will email you my address

Thanks so much! 
Tobaloidee

**Comment by b0bi79** [comment]
@Tobaloidee I added your name to the README.md.
Thank you for your contribution.
