### ISSUE TITLE
HYPERLINK error: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by rethabile-dev** [ClosedXML/ClosedXML.Report#320]
HYPERLINK produces an error for links in ranges to other cells. It works fine for external `http://` links.

i.e.

&=HYPERLINK("#'{{item.Name}}'!A1","{{item.Name}}") throws `Collection was modified; enumeration operation may not execute.`

Edit:
Looks like the workaround provided here solves the issue. i.e. via `Insert -> Hyperlink`
https://github.com/ClosedXML/ClosedXML.Report/issues/208#issuecomment-888061011

**Comment by Pankraty** [comment]
I will appreciate if you attach a template and provide some reproduction code so I could investigate the issue.

**Comment by rethabile-dev** [comment]
Hi @Pankraty, Thanks for the reply.

It looks like version 0.2.8 solves the issue, so I'm upgrading to version 0.2.8 and closing the issue instead.
