### ISSUE TITLE
Failed to generate a file from a template

### ISSUE THREAD

**Issue by c4bo3l** [ClosedXML/ClosedXML.Report#324]
ClosedXML.Report: 0.2.8

Getting error: Method not found: 'ClosedXML.Excel.IXLRange ClosedXML.Excel.IXLPivotTable.get_SourceRange()'.

**Comment by Pankraty** [comment]
What version of ClosedXML are you using?

**Comment by c4bo3l** [comment]
I am using ClosedXML 0.102

**Comment by Pankraty** [comment]
ClosedXML.Report: 0.2.8 is only compatible with ClisedXML 0.101. Try downgrade the dependency or build  a custom version of .Report from develop branch.
0.2.9 will come shortly and it'll be supporting 0.102

**Comment by c4bo3l** [comment]
Awesome, thanks.

**Comment by Pankraty** [comment]
Oh 😮

**Comment by jcageman** [comment]
> ClosedXML.Report: 0.2.8 is only compatible with ClisedXML 0.101. Try downgrade the dependency or build a custom version of .Report from develop branch. 0.2.9 will come shortly and it'll be supporting 0.102

This is still not the case? When will you release 0.2.9? Currently upgrading to the latest version of both packages is impossible due to this, which is not really nice.

**Comment by smakaiberriesandco** [comment]
@Pankraty when 0.2.9 is expected? in .net 8 its impossible to use ClosedXml newest version with ClosedXml.Report.
