### ISSUE TITLE
ClosedXML to 0.102.2

### ISSUE THREAD

**Issue by Reivaj810** [ClosedXML/ClosedXML.Report#343]
Migration to version ClosedXML 0.102.2 to can use the new version of ClosedXML, and upgrade the test to Net 8 and most of the references. 

I have a Branch to make a PR

**Comment by Pankraty** [comment]
@Reivaj810 hi! If you can make a PR that would be awesome!

**Comment by Reivaj810** [comment]
Sure, I already had a branch ready yo made the PR, but I'm looking how do the PR?

**Comment by Pankraty** [comment]
Closed via #345
