### ISSUE TITLE
'IXLWorkbook' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by fingers10** [ClosedXML/ClosedXML.Report#372]
I see this issue in `.NET 9 blazor wasm` app. I'm trying to build a in-browser demo for closed xml report - https://ilovedotnet.org/blogs/generate-excel-report-using-closed-xml-in-dotnet/

Nuget Added:
```csproj
<PackageReference Include="ClosedXML" Version="0.104.2" />
<PackageReference Include="ClosedXML.Report" Version="0.2.10" />
```

```cs
var file = await HttpClient.GetStreamAsync("./files/ILoveDotNetContentTemplate.xlsx");
        
var template = new XLTemplate(file);

template.AddVariable(complexData);
template.Generate();
template.Workbook.Worksheets
    .Worksheet(template.Workbook.Worksheets.First().Name)
    .ColumnsUsed()
    .AdjustToContents();

using var stream = new MemoryStream();
template.SaveAs(stream);
```

Here is the error message

> The type 'IXLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.102.2.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b'.

When I try to install `ClosedXML 0.102.2.0`, WASM app breaks... Any hints on where to go from here?

**Comment by jahav** [comment]
It's not going to work with 0.104.2. The 0.102.2 is the last working version. 

ClosedXML is going through significant refactoring/changes (including api breakage) and ClosedXML.Report doesn't get much love in the meantime. It mostly works with limited version combinations. 

PR to update to 0.104 (105 Tbh) #368.
