### ISSUE TITLE
Clarification needed to populate table

### ISSUE THREAD

**Issue by touhiDroid** [ClosedXML/ClosedXML.Report#38]
I have read [the doc on Flat Tables](https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables), but can't understand the connection between the `Orders` & the template's `item` element.

What I was trying to achieve:
I have the following template:
![image](https://user-images.githubusercontent.com/2558197/43835827-1f4e70ee-9b35-11e8-90cc-bce814ec5760.png)

I have to print data from the following class:
```
class SoldItemsReport
    {
        public string Company { get; set; }
        public string Branch { get; set; }
        public string Phone { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }

        public List<SoldItem> SoldItems { get; set; }

        public SoldItemsReport(string company, string branch, string phone, string fromDate, string toDate, object items)
        {
            Company= company;
            Branch = branch;
            Phone = phone;
            FromDate = fromDate;
            ToDate = toDate;
            SoldItems = items as List<SoldItem>;
        }
    }
```
The data setup code is copied from [the above mentioned doc](https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables) & now like the following:
```
string outputFile = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/report.xlsx";
            try
            {
                using (var template = new XLTemplate(@".\report_template_sold_items.xlsx"))
                {
                    // NOTE: The following variables are also working perfectly, besides the grouped model data
                    // template.AddVariable("Company", Pref.GetRestaurantName());
                    // template.AddVariable("Branch", Pref.GetBranchName());
                    // template.AddVariable("Phone", Pref.GetBranchPhone());
                    // template.AddVariable("FromDate", fromDateStr);
                    // template.AddVariable("ToDate", DateTime.Now.ToString("yyyy-MM-dd"));

                    var items = ListViewSoldItems.Items;
                    template.AddVariable(new SoldItemsReport("My Company",
                        "Main Branch",
                        "+182374870",
                        fromDateStr,
                        DateTime.Now.ToString("yyyy-MM-dd"),
                        items));

                    template.Generate();
                    template.SaveAs(outputFile);
                }
                ShowSuccess("Path: " + outputFile);
                //Show report
                Process.Start(new ProcessStartInfo(outputFile) { UseShellExecute = true });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.StackTrace);
                ShowError("Sorry! Cannot generate XLSX now.");
            }
```
Both the commented `AddVariable` & model-packaged `AddVariable` methods are working for the plain fields, but range-variables (range is named as `SoldItems`) are **not setting data** rather printing the tags as it is (like: `{{item.OrderCount}}`, `<<sum>>` etc.).

Am I missing any very basic point? I have gone through all the basic docs of this library with my naive knowledge of spreadsheet processing, but with no luck. Please give me any kind of hint/clarification about which I may have missed.

**Comment by Pankraty** [comment]
Did you define a named range called {{SoldItems}} and referring to {{A7:F8}} range?
Like this:
![image](https://user-images.githubusercontent.com/19576939/43840468-d30464da-9b31-11e8-8607-f2be15427000.png)

**Comment by touhiDroid** [comment]
Yes, I have created the named range - & 2 times : one with `{{B7:F8}}` range & another with `{{A7:F8}}` range. But both of those deliver the same result mentioned in the post.

Screenshot from the MS Excel name-manager:
![image](https://user-images.githubusercontent.com/2558197/43841355-c903666c-9b44-11e8-95c9-84372ab6e6d1.png)

**Comment by Pankraty** [comment]
Try to remove the first one (for `B7:F8`) and rename another to `SoldItems` as its name must coincide to the property name.

**Comment by touhiDroid** [comment]
I actually renamed the property to `SoldItems2` while introduced the range-name `SoldItems2`.

But still - I have removed the 1st one (for `B7:F8`) and renamed the other to `SoldItems` (also renaming my property back to `SoldItems`) & with no luck.

**Side-question:** Is there any reason we need the empty `A*` column for this range?
My guess - ClosedXML library puts some log for errors in that column (?).

**Comment by Pankraty** [comment]
No, the empty column may be used for placing service tags that are applied to the row. Currently, there are only two tags affecting rows (`RowsFit` and `Delete`) but this list may be extended in future. The documentation section regarding tags (https://closedxml.github.io/ClosedXML.Report/docs/ru/More-options) has not been translated into English yet :( Sorry for that.

For your original issue, I'm afraid I need a complete code example and your template for I could diagnose what is the problem.

**Comment by b0bi79** [comment]
To the range, you can also applied the tags `Pivot`, `SummaryAbove`, ` DisableGrandTotal`, `OnlyValues`,` AutoFilter` and `ColsFit`.
These tags must be added in the lower left cell of the range.

**Comment by touhiDroid** [comment]
@b0bi79 , I needn't add those tags - the same template has worked in [the demo project](https://github.com/touhiDroid/ClosedXmlReportDemo).

Afterwards, I have discovered that my argument `SoldItems` was not properly initialized as I was casting the `object` in constructor to `List<SoldItem>` directly. Now, I have copied the list by loop:
```
                    List<SoldItem> list = new List<SoldItem>();
                    foreach (SoldItem si in ListViewSoldItems.Items)
                        list.Add(si);
                    template.AddVariable(new SoldItemsReport("My Company",
                        "Main Branch",
                        "+182374870",
                        fromDateStr,
                        DateTime.Now.ToString("yyyy-MM-dd"),
                        items));

```
& have updated the constructor as:
```

        public SoldItemsReport(string company, string branch, string phone,
            string fromDate, string toDate, List<SoldItem> items)
        {
            Company = company;
            Branch = branch;
            Phone = phone;
            FromDate = fromDate;
            ToDate = toDate;
            SoldItems = items;
        }
```

Everything is working pretty smoothly now.
So no gap of documentation in this library - thanks for your helps & obviously the library.

**Comment by Pankraty** [comment]
Ah, I suspected this!

Btw, you can use list's AddRange() method in order to avoid loop. Or simply use the linq .ToList() method. 

In addition, I'd recommend to make fromDate and toDate fields being of type DateTime and perform the formatting in the Excel template.

**Comment by touhiDroid** [comment]
@Pankraty, those are certainly some good suggestions! Actually I needed to convert the date to string ahead of this part in the real project for some other processes. 

Btw, thanks a lot :D
