### ISSUE TITLE
Adding support for comment templating.

### ISSUE THREAD

**Issue by wakuflair** [ClosedXML/ClosedXML.Report#39]
First thank you guys, this is a great repo!

I added a comment to a cell, and inside the comment I wrote an expression like `{{item.Comment}}`,
but in the generated file, the comment is missing.

I looked the code, and it seems that comment templating is not supported.
Will you consider supporting this feature?

**Comment by wakuflair** [comment]
Hi @b0bi79 

**template capture:**

![image](https://user-images.githubusercontent.com/3471718/44614527-61bafc00-a859-11e8-99cf-e8517eee7b9c.png)

**code pieces:**

~~~ c#
    class Program
    {
        private class Person
        {
            public string Name { get; set; }
            public int Age { get; set; }
        }

        static void Main(string[] args)
        {
            var people = new List<Person>
            {
                new Person {Name = "Alice", Age = 23},
                new Person {Name = "Bob", Age = 50},
            };
            using (var stream = new FileStream("TemplateWithComment.xlsx", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                using (var template = new XLTemplate(stream))
                {
                    template.AddVariable("People", people);
                    template.Generate();
                    template.SaveAs("report.xlsx");
                }
            }
        }
    }
~~~

**generated file capture:**
![image](https://user-images.githubusercontent.com/3471718/44614546-c413fc80-a859-11e8-9175-4b308c275517.png)


As you can see, the comment "{{People.Count}}" is not evaluted, and the comment in vertical table is totally missing.

**Template:**
[TemplateWithComment.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/2320308/TemplateWithComment.xlsx)

**Comment by b0bi79** [comment]
Now I understand what you want.
I can add this to the next version, which I plan to release in about a month. If you want to contribute to this project, then you can add PR with this feature.

**Comment by b0bi79** [comment]
Done
