### ISSUE TITLE
Error in template while adding employee list

### ISSUE THREAD

**Issue by vinay13mar** [ClosedXML/ClosedXML.Report#44]
Hi
I am getting error while adding the list of employee in template.
Error: 

The   range does not meet the requirements of the list ranges. For details, see the   documentation.
--
Please check the code:
`   
  var people = new List<Employee>
            {
                new Employee {Name = "Alice", Address = "dfsasdasdasd",Phone="312312312"},
                  new Employee {Name = "Alice1", Address = "dfsasdasdasd1",Phone="2131232"},
                     new Employee {Name = "Alice3", Address = "dfsasdasdasd3",Phone="5645"}
            };
            template.AddVariable("employee", people);
            template.Generate();
            template.SaveAs(outputFile);
public class Employee
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }

`
Please check the error screen shot.
**Template:**

![screenshot_2](https://user-images.githubusercontent.com/17878669/46669464-2304b980-cbed-11e8-9822-cd57c9b7cdd8.png)

**Output:**

![screenshot_1](https://user-images.githubusercontent.com/17878669/46669463-2304b980-cbed-11e8-98bc-8714a1e5fbc9.png)

Note : for string and integer values it's working fine. but issue with list

**Comment by b0bi79** [comment]
@vinay13mar can you attach template?

**Comment by b0bi79** [comment]
Your template does not meet the requirements for lists.
The wiki article will help you https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

**Comment by vinay13mar** [comment]
Hi
Please check the template

[template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/2460583/template.xlsx)

**Comment by b0bi79** [comment]
I modified your template. Look at what I changed - I created a range with the name of your variable ("empoloyee"), which includes a row with formulas, a row of options under the formulas and a column of options to the left of the table.

[template.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/2460708/template.xlsx)
![templateimg](https://user-images.githubusercontent.com/1150085/46674734-9a364f80-cbe5-11e8-959c-76093823cfb3.png)

Read more about it here  https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables

**Comment by vinay13mar** [comment]
Hi b0bi79,

Thanks you so much. It works like charm. Thanks you so much. you saved my day

Thanks
Vinay Singh
