### ISSUE TITLE
Embed file(pdf,text,zip etc) in in excel

### ISSUE THREAD

**Issue by vinay13mar** [ClosedXML/ClosedXML.Report#45]
Hi 

I tried to embed file in excel. But did not get any success. Is is possible by using closeXML.Report.

Thanks
Vinay

**Comment by b0bi79** [comment]
I think it does not allow to make ClosedXML.

**Comment by b0bi79** [comment]
If this feature appears in ClosedXML, then ClosedXML.Report will automatically support this feature.

**Comment by vinay13mar** [comment]
Hi
Thanks for your quick reply. do u have idea about how we can do it. or any reference link.

Thanks
Vinay
