### ISSUE TITLE
Big report file causes IsolatedStorageException {"Unable to determine the identity of domain."}

### ISSUE THREAD

**Issue by melofon** [ClosedXML/ClosedXML.Report#49]
This is a known issue for ClosedXML library when working with big files - https://github.com/ClosedXML/ClosedXML/issues/264
And looks like for ClosedXML it was solved in version 0.93.1. ClosedXML.report library was installing ClosedXML 0.92.1.0. I have tried to update it and got a message "The type 'IXLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.92.1.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b'".

Is there a way to avoid domain issue in ClosedXML.report?

**Comment by melofon** [comment]
Yep, thanks, that's good. Actually the problem is that when in ClosedXML I'm trying to call `var template = new XLTemplate("TestReport.xlsx");` it's says that "The type 'IXLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.92.1.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b'.". So it looks like with the last version of ClosedXML.Report one must be using ClosedXML 0.92.1.0. Is it possible to use ClosedXML.report 0.1.1.1 with ClosedXML 0.93.1? Maybe I'm just doing something wrong...

**Comment by b0bi79** [comment]
@melofon I am currently working on updating the ClosedXML version in ClosedXML.Report. Work is a lot because Many things have changed in ClosedXML.

**Comment by melofon** [comment]
Thank you guys for your awesome work. Regarding this issue - I have several reports with printing area 10k*200 cells, so it looks like ClosedXML should be used directly instead of ClosedXML.Report for my current needs. Is there a way I could help with transition ClosedXML.Report to latest ClosedXML?

**Comment by b0bi79** [comment]
@melofon, thanks for the suggestion for help. My biggest problem right now is that 15 tests do not pass. Each test takes about one day of work. And I can only do this 2 days a week ...

**Comment by igitur** [comment]
@pankraty Says there are 2 issues in ClosedXML that must be solved first before ClosedXML.Report can be upgraded.

**Comment by b0bi79** [comment]
Hi @igitur, maybe @Pankraty has advanced further than me, but now I have this picture
![2018-11-07_11-41-59](https://user-images.githubusercontent.com/1150085/48120140-584f0680-e282-11e8-935e-04e3ea1d3709.png)

**Comment by b0bi79** [comment]
@melofon can you test your big reports with new released version 0.2.0-beta1?

**Comment by b0bi79** [comment]
New release should solve this issue. If the problem persists, then you can reopen the issue.
