### ISSUE TITLE
How to implement row number for each group?

### ISSUE THREAD

**Issue by Hoannd2** [ClosedXML/ClosedXML.Report#62]
I want to add row number (1, 2, 3,...) for each group. Please show me how to do that?

**Comment by b0bi79** [comment]
You can use for it Excel formula ROW. Do not forget to escape formula like `&=ROW()-4`
Also you can use additional field with numbers in your data model.

**Comment by Hoannd2** [comment]
Thank you,
but if have some groups, and each group number restart at 1, &=ROW()-4 is not the solution. the additional field in the data model has problem with <<sort>>

for example:
Group A 
1  Col2  Col3
2  Col2  Col3
Group B
1  Col2  Col3
2  Col2  Col3
3  Col2  Col3

**Comment by b0bi79** [comment]
Sorry, please explain what problem has a solution with additional fields?

**Comment by Hoannd2** [comment]
Aditional fields mean i can not use <<sort>> tag in the template file because the sort order is fixed in the code.

**Comment by b0bi79** [comment]
Sorry for long answer.
You can use variable index like {{index+1}}

**Comment by b0bi79** [comment]
Oh, I forgot that you need the line number inside the group. Then I can recommend you to use the formula as: =COUNTIF($B$2:B2, B2)
Example:

Group A
=COUNTIF($B$2:B2,B2) | Group A | Col2 | Col3
=COUNTIF($B$2:B3,B3) | Group A | Col2 | Col3
Group B
=COUNTIF($B$2:B5,B5) | Group B | Col2 | Col3
=COUNTIF($B$2:B6,B6) | Group B | Col2 | Col3
=COUNTIF($B$2:B7,B7) | Group B | Col2 | Col3
