### ISSUE TITLE
Error loading report generated on ReoGrid

### ISSUE THREAD

**Issue by Jozelom** [ClosedXML/ClosedXML.Report#63]
Good morning, I am creating a report which is generated successfully, but when loading it into the ReoGrid control (https://github.com/unvell/ReoGrid) I get an error and it does not open it.

But if I generate an excel with ClosedXML (not ClosedXML.Report) it opens without problems
There is a difference in the generation of the two

If I open and save the file (Report) with excel, ReoGrid opens it without problems

The code to generate the Report is as follows
![image](https://user-images.githubusercontent.com/38925156/50098914-e526a180-01ea-11e9-94c2-b61f2c2e3923.png)
If anyone has had this problem and has solved it, help me, thanks

**Comment by b0bi79** [comment]
With which version of ClosedXML did you create a "good" excel file? Perhaps the reason is the version of ClosedXML. Now ClosedXML.Report uses ClosedXML version 0.92, although version 0.94 has already been released.
If this is not the case, then the case may be in the template on the basis of which you generate a report. To find the final solution, it is important to know which part of the file does not like ReoGrid.

**Comment by Jozelom** [comment]
the version I use for the "good" excel is 0.92

I was able to deduce possible 2 problems:

1- Apparently Reogrid is only recognizing 200 rows of generated report and when it is in index 200 it can not get its header, which does not happen when the file is opened and saved by Excel
![image](https://user-images.githubusercontent.com/38925156/50157093-8589ce00-029e-11e9-822f-97f785e53808.png)

2-Reviewing the issues of Reogrid I found a similar error that occurred when "An Excel sheet that contains multi-line text can cause NullReferenceException to be the exception". But according to Reogrid this has already been solved (https://github.com/unvell/ReoGrid/issues/53)
 
Attached the 2 Excel files, OK is "good"
[Reporte.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/2690693/Reporte.xlsx)
[ReporteOK.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/2690694/ReporteOK.xlsx)

Thanks for your help and your time

**Comment by b0bi79** [comment]
You said that your OK-file was generated with ClosedXML. But as far as I can see the ReporteOK.xlsx file is obtained using Excel. Could you send the file generated by ClosedXML?

**Comment by Jozelom** [comment]
Ok, I send the file generated with ClosedXML
This file has no design
[Reporte.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/2691761/Reporte.xlsx)

**Comment by b0bi79** [comment]
I looked at the ReoGrid code and I'm sure the problem is there.
Your "Issue-file" opens fine in Excel, so I think you need to contact ReoGrid, because this problem is in the ReoGrid code.

**Comment by Jozelom** [comment]
OK, Thanks for your time.
