### ISSUE TITLE
Dictionary as data source not work

### ISSUE THREAD

**Issue by Fox2726** [ClosedXML/ClosedXML.Report#64]
Could you give us a sapmle?
We try to write "dic" in templates. but it's not work.
Thanks.

**Comment by b0bi79** [comment]
It need implement [Dynamic Data Classes](https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#dynamic-data-classes) for `Dictionary` parameters.

**Comment by Fox2726** [comment]
Did it possible use dynamic class (created in runtime) as data source in furture?

**Comment by Fox2726** [comment]
I found a away to use dynamic class by Dynamic Data Classes. Thanks.
