### ISSUE TITLE
Pivot table's number of fields limit

### ISSUE THREAD

**Issue by Fox2726** [ClosedXML/ClosedXML.Report#67]
Did the pivot table have the limit of column count will not able work? as i try it and i get a error when the number of columns more than 11.

**Comment by Fox2726** [comment]
@b0bi79  i found it. the same issue as below. And ever the column did not tag to 
<<row>>, <<column>>, <<page>> also could not be null or empty.
-----------------------------------------------------------------------------------------------------------
In the data for which there is a grouping (tags <<row>>, <<column>>, <<page>>) there should not be null or empty lines. Blank lines must be replaced by at least a space. The used version of ClosedXML (v0.92) did not correctly process such data. I think that in the new version of ClosedXML this problem should be fixed.

**Comment by b0bi79** [comment]
Thanks, I will check it on the new version

**Comment by mlivingstonNE** [comment]
I have a similar issue. I have a table which varies in number of rows but is generally 35,000 to 40,000. The number of columns is static at 10. When creating a pivot table, the maximum number of rows that will correctly translate to a pivot table is 32,895 (that was fun determining). Therefore, I not only can I not create a complete pivot table, I also cannot use LastRowUsed to define it.

I'm using v0.94.

**Comment by b0bi79** [comment]
If this is not a limitation of MS Excel, then this may be a limitation of ClosedXML. Can you provide the problem result file?

**Comment by mlivingstonNE** [comment]
Certainly.
[Test2.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3074388/Test2.xlsx)

**Comment by b0bi79** [comment]
@mlivingstonNE please also attach the template. Thanks.

**Comment by mlivingstonNE** [comment]
There is no template. But here is the code from the application:

static void Main(string[] args)
        {
            String fileName = "DeliveryCompliace " + DateTime.Today.ToString("MMddyyyy") + ".xlsx";
            String runTime = DateTime.Now.ToString("MM/dd/yyyy HH:mm");
            String reportDate = DateTime.Today.ToLongDateString();
            
            // Create Workbook
            XLWorkbook wb = new XLWorkbook();
            // Create Worksheet
            IXLWorksheet ws = wb.Worksheets.Add("Data");

            
            // Fill table from stored procedure
            SqlConnection sqlConnection = new SqlConnection(Properties.Settings.Default.conString);
            SqlCommand sqlCommand = new SqlCommand("dbo.cex_DScanCompData", sqlConnection);
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.Parameters.Add("@dDate", SqlDbType.DateTime).Value = reportDate;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            DataTable dataTable = new DataTable();
            sqlDataAdapter.Fill(dataTable);

            // Insert Datatable data
            IXLTable table = ws.Cell(1, 1).InsertTable(dataTable, "Data", true);

            // Fix OrderTrackingID format in ws
            ws.Column(5).CellsUsed().Style.NumberFormat.Format = "#.000000";
            // Adjust column widths in ws
            ws.Columns().AdjustToContents();

            // Pivot Table
            // Add new worksheet
            IXLWorksheet ps = wb.Worksheets.Add("Report");

            // Create pivot table
            var totalRows = ws.LastRowUsed().RowNumber() - 5;
            var totalColumns = ws.LastColumnUsed().ColumnNumber();
            IXLPivotTable pt = ps.PivotTables.Add("PivotTable", ps.Cell(3, 1), ws.Range(1,1,totalRows,totalColumns)); // Max rows 32,895!!

            pt.RowLabels.Add("TerminalName").SetCollapsed();
            pt.RowLabels.Add("Driver").SetCollapsed();
            pt.RowLabels.Add("ConsCompany", "Client").SetCollapsed();

            pt.Values.Add("PkgCount").SetSummaryFormula(XLPivotSummary.Sum);
            pt.Values.Add("DScan").SetSummaryFormula(XLPivotSummary.Sum);
            pt.Values.Add("MScan").SetSummaryFormula(XLPivotSummary.Sum);
            pt.Values.Add("NScan").SetSummaryFormula(XLPivotSummary.Sum);

            //For testing purposes
            IXLWorksheet ws3 = wb.Worksheets.Add("Test");
            ws3.Cell("A1").Value = totalRows;
            ws3.Cell("A2").Value = totalColumns;

            // Save workbook
            wb.SaveAs(@"C:\Users\CEsolutions\Documents\Test2.xlsx");
        }

**Comment by b0bi79** [comment]
@igitur I think it need to create an issue in ClosedXML?

**Comment by mlivingstonNE** [comment]
I will do that.
