### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by MasterSlynx** [ClosedXML/ClosedXML.Report#70]
There is an exception - here is full stack:

>  	ClosedXML.Report.dll!ClosedXML.Report.Parameter.Parameter(string name, object value) Line 72	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeTemplate.RenderCell(object[] items, int i, ClosedXML.Report.FormulaEvaluator evaluator, ClosedXML.Report.TemplateCell cell) Line 276	C#
>	ClosedXML.Report.dll!ClosedXML.Report.RangeTemplate.HorizontalTable(object[] items, ClosedXML.Report.FormulaEvaluator evaluator) Line 334	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeTemplate.Generate(object[] items) Line 149	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeTemplate.RenderSubrange(object item, ClosedXML.Report.FormulaEvaluator evaluator, ClosedXML.Report.TemplateCell cell, ClosedXML.Report.Options.TagsList tags, ref int iCell, ref int row) Line 291	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeTemplate.VerticalTable(object[] items, ClosedXML.Report.FormulaEvaluator evaluator) Line 182	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeTemplate.Generate(object[] items) Line 153	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeInterpreter.EvaluateValues(ClosedXML.Excel.IXLRange range, ClosedXML.Report.Parameter[] pars) Line 146	C#
 	ClosedXML.Report.dll!ClosedXML.Report.RangeInterpreter.Evaluate(ClosedXML.Excel.IXLRange range) Line 36	C#
 	ClosedXML.Report.dll!ClosedXML.Report.XLTemplate.Generate() Line 83	C#

Exception is caused by null item in object array passed to RenderCell method. There are two ways to fix it - first allow null values in array if array type is specified (other than object[]), second - just guard it to not to throw it as internal null reference but add some explanation in exception details.

I leave solution to author but IMHO null values (like string) are pretty common and should be supported in same way as empty strings.

**Comment by b0bi79** [comment]
thanks, I will fix it
