### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by SigmaSoftSol** [ClosedXML/ClosedXML.Report#71]
Hi,
  How can I highlight the row based on a condition.
for example I have a value in cell A and based on the cell value I need to highlight the row with a color.
How can I achieve this.
Thanks & Regards,
Seshu Kumar.

**Comment by Pankraty** [comment]
Easy-peasy
![image](https://user-images.githubusercontent.com/19576939/53315302-e7d4ff80-38db-11e9-90fa-504bcecb652e.png)

**Comment by SigmaSoftSol** [comment]
I think, The condition should be in the report.  I ko we can highlight the cells based on a condition in the excel.  But I want this to be from the excel report template.

**Comment by SigmaSoftSol** [comment]
You closed the issue with an in appropriate answer.

**Comment by Pankraty** [comment]
>  I ko we can highlight the cells based on a condition in the excel.

That's exactly what conditional formatting does. ClosedXML.Report does not provide possibilities to format the output result other than ordinary styles and conditional formats.
