### ISSUE TITLE
The generated file does not open in Excel

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML.Report#82]
I am working on introducing Pivot styles. For testing tests are used PivotTests.Simple. When performing the specified test with the tPivot5_Static.xlsx template, a file is generated that does not open in Excel.

Commit https://github.com/ClosedXML/ClosedXML.Report/pull/81 compiled with ClosedXML https://github.com/ClosedXML/ClosedXML/pull/1189

**Comment by igitur** [comment]
When you say the file doesn't open in Excel, do you mean that Excel complains that the file is corrupt?

**Comment by b0bi79** [comment]
Yes

**Comment by b0bi79** [comment]
I noticed that the problem does not occur if the PivotTable data is empty. From this I can assume that there may be an error related to the pivotCacheDefinition section.

**Comment by b0bi79** [comment]
Я нашёл. В pivotCacheRecords1.xml поле "Tax rate" не содержит данных. Если я добавлю данные к этому полю, то ошибка пропадает. 
Было:
```
<x:cacheField name="Tax rate">
	<x:sharedItems containsSemiMixedTypes="0" containsString="0" containsNumber="1" minValue="0" maxValue="8.5" count="3" />
</x:cacheField>
```
Исправление:
```
<x:cacheField name="Tax rate">
	<x:sharedItems containsSemiMixedTypes="0" containsString="0" containsNumber="1" minValue="0" maxValue="8.5" count="3">
		<x:n v="4.5" />
		<x:n v="0" />
		<x:n v="8.5" />
	</x:sharedItems>
</x:cacheField>
```
Поле "Tax rate" участвует в PivotTable как ColumnField. Сценарий для воспроизведения:
1. Открыть файл, в котором есть PivotTable
2. Изменить данные, на которые ссылается PivotTable
3. Сохранить файл.

**Comment by b0bi79** [comment]
На самом деле там две проблемы. Это решает только одну. Решение для второй проблемы пока не нашёл.

**Comment by b0bi79** [comment]
Found the second problem, because of which the file opens with an error.
In the pivotTable1.xml file, the location element has the property ref = "B3", if I change this value to ref = "B3: L211", then the file is opened without errors.

**Comment by b0bi79** [comment]
The reason that in the pivotCacheDefinition the TaxRate field was not filled in was that the file was generated based on a template in which two summary tables are constructed from data from the same data table. In this case Excel creates one pivotCacheDefinition file, and ClosedXML while caches the last Pivot overwrites the cache for the first Pivot.

**Comment by b0bi79** [comment]
Closed by https://github.com/ClosedXML/ClosedXML/pull/1196
