### ISSUE TITLE
Is there a way to display rows horizontal rather then vertically. 

### ISSUE THREAD

**Issue by cordasfilip** [ClosedXML/ClosedXML.Report#84]
I was unable to find in documentation if there is a way to display items in one next to the other rather one under the other.  Range horizontal displays everything horizontally. What I need is items to be displayed inline like so:
Row1 | Row2 | Row3 |
Col1   | Col1  | Col1  |
Col2   | Col2  | Col2  |
Rather then 
Row1 | Col1 |  Col2|
Row2 | Col1 |  Col2|
Row3 | Col1 |  Col2|
I am not sure if there is a pivot function for this,the docs are in Russian.

**Comment by b0bi79** [comment]
Yes @cordasfilip, I see a problem. Horizontal ranges were not tested, because still no one was interested in them. In the near future I will fix it.

**Comment by b0bi79** [comment]
The issue has been fixed.
You can wait for the release or download the fixed and compiled binary here. https://ci.appveyor.com/project/ClosedXML/closedxml-report/builds/24533369/job/94kf3anvl9bkq9qa/artifacts

**Comment by b0bi79** [comment]
If you need an example of how to get a horizontal report, then see the test [XlTemplateTests.HorizontalRangeTest](https://github.com/ClosedXML/ClosedXML.Report/blob/e8200ae89262da01c63c29ac1b633edf319d1e98/tests/ClosedXML.Report.Tests/XlTemplateTests.cs#L355) and template [tests\Templates\HorizontalRange.xlsx](https://github.com/ClosedXML/ClosedXML.Report/blob/develop/tests/Templates/HorizontalRange.xlsx)

**Comment by cordasfilip** [comment]
Wow thank you for the quick response that was quick. Do you have any date on the release?

**Comment by b0bi79** [comment]
I can not say when the release will be. There are quite a few tasks that are still unsolved. In addition, I can only release a release when ClosedXML is released.

**Comment by cordasfilip** [comment]
Sorry to say but this doesn't seam to be working. I tested this with the templet you provided and this was working but when I started changing things it wasn't working. I deleted the merged column (D)from the template and it was not working any more. I also tried to do several different templates with my data and it wasn't working.

**Comment by b0bi79** [comment]
Put your template please.

**Comment by cordasfilip** [comment]
[HorizontalRange (1).xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3187612/HorizontalRange.1.xlsx)

**Comment by cordasfilip** [comment]
Just to mention seams to have some negative effects on the regular range as well the first row is moved one column to the right

**Comment by b0bi79** [comment]
Sorry. Little typo, big bug. 
Fixed.
https://ci.appveyor.com/project/ClosedXML/closedxml-report/build/job/3bt0i2eq505yypxx/artifacts

**Comment by cordasfilip** [comment]
Tested the new dll it works, but there is a minor issue that the width of the columns is not preserved.

**Comment by b0bi79** [comment]
Try this https://ci.appveyor.com/project/ClosedXML/closedxml-report/build/job/5aqgli06r4r570ow/artifacts

**Comment by cordasfilip** [comment]
Sorry wasn't near my pc last night couldn't test, there seam to be no binaries.

**Comment by b0bi79** [comment]
For some reason, the address has changed
https://ci.appveyor.com/project/ClosedXML/closedxml-report/build/job/vklr1f9avqplikvg/artifacts

**Comment by cordasfilip** [comment]
Works grate now, if I find anything else I will open a new issue.
