### ISSUE TITLE
Is there a way to conditional coloring of rows?

### ISSUE THREAD

**Issue by tarasverq** [ClosedXML/ClosedXML.Report#87]
Hello!

I'm trying to implement an report with this lib.
And i have a question:

How can i colorize some data rows in report basing on data?
For example:  i want to colorize row of subgroup in blue in case of existence of best price,
otherwise, if there two or more equal best prices i want to colorize this two or more rows in yellow.
How to do this? :) 
![image](https://user-images.githubusercontent.com/8226275/58409748-62e3b880-8079-11e9-9248-c727f678444f.png)

**Comment by b0bi79** [comment]
I see here three ways to colorize the rows:
1. Using only the standard Excel function - Conditional formatting. For your example, you can use a formula like this: `=AND($D2=MAX($D$2:$D$2))`
2. Add an additional property to the model that determines the color of the row. The value from this field is output to the hidden column. Next use Conditional Formatting.
3. Develop a new tag, inheriting from OptionTag.
