### ISSUE TITLE
How to insert Image?

### ISSUE THREAD

**Issue by anicething** [ClosedXML/ClosedXML.Report#91]

**Comment by b0bi79** [comment]
Do you want to insert an image statically or dynamically? Static image can be inserted into the template. Dynamic image insertion ClosedXML.Report does not yet support. I will add this feature for the next version. While this is not, you can develop your tag. As an example, you can see how the OnlyValuesTag class is implemented.

**Comment by TomasWeg** [comment]
Any update?

**Comment by b0bi79** [comment]
Now I am very busy and cannot find time to work on this project. I'm sorry.
This is an open source project and you can contribute by adding this functionality.

**Comment by Slowrider1969** [comment]
Just checking to see if there has been any change to this one?
Thanks

**Comment by b0bi79** [comment]
Added a new tag <Image>.

**Comment by maxft2911** [comment]
hi all, can we use the tag <Image> in ClosedXml.Reports?
