### ISSUE TITLE
nullreferenceexception with RowsFit tag when empty data source.

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML.Report#95]
As @BenKmann wrote:

> I still get an Exception. Nullref because of the RowsFitTag.
>
> bei ClosedXML.Report.Options.RowsFitTag.Execute(ProcessingContext context)
> bei ClosedXML.Report.Options.TagsList.Execute(ProcessingContext context)
> bei ClosedXML.Report.RangeTemplate.RangeTagsApply(IXLRange range, Object[] items)
> bei ClosedXML.Report.RangeInterpreter.EvaluateValues(IXLRange range, Parameter[] pars)
> bei ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
> bei ClosedXML.Report.XLTemplate.Generate()
> 
> Condition is, Empty Datasource + i use the following Tags in Column A `<<summaryabove>><<DisableGrandTotal>><<RowsFit>>`
> 
> RowsFit than is pretty unhappy about the 0 rows. If i Remove `<<RowsFit>>` the Exception disappears.

**Comment by b0bi79** [comment]
@BenKmann, hi. I'm trying to reproduce the error with RowsFit, but I can't. Please attach your template.

**Comment by b0bi79** [comment]
There is no confirmation of the problem. @BenKmann did not answer.

**Comment by b0bi79** [comment]
@terekhovkg Thanks, I will check this

**Comment by davija** [comment]
When is this going to be released?  This is a blocking issue for me.

**Comment by b0bi79** [comment]
At the moment, only one fix is ready for release. I don't want to release one version for every bug fix. At the same time, I don’t have time to work on the project now, I’m waiting for a vacation. I think the next version will be released in June.

**Comment by davija** [comment]
I understand that you don't want to be doing a lot of releases, or a release per bugfix, but considering the NRE in a case that is somewhat normal, this should be considered a candidate for a release, even if it is the only feature in that release.

**Comment by igitur** [comment]
@davija This is open source. If you're unhappy with the release cycle, you can do your own build. The author of this library doesn't owe anybody anything. He is already sacrificing her personal time to maintain this library. For free.

**Comment by davija** [comment]
@igitur Yes, I am well aware of that.  However, when you have a library that people use and depend on with a somewhat critical bug in a basic feature, it is nice to see progress on getting those bugs fixed and released once fixed (it was fixed ~5 months ago).

Additionally, it doesn't take that long to do the release process and publish to nuget (I pretty much have already forked, built and published to our own repository).
