### ISSUE TITLE
Is it possible to deliver this file in ASP.NET instead of saving to path?

### ISSUE THREAD

**Issue by fingers10** [ClosedXML/ClosedXML.Report#97]
Dear Team,

I'm a big fan of ClosedXML which I used to download the excel to browser. Now I'm planning to move from Crystal Reports. So planning to see if ClosedXML.Report will suit my needs. I have very basic reports which I can cover from the ClosedXML.Report docs. But I'm stuck at this point. Like [Deliver-an-Excel-file-in-ASP.NET](https://github.com/ClosedXML/ClosedXML/wiki/Deliver-an-Excel-file-in-ASP.NET), is it possible to do the same in ClosedXML.Report? 

Please assist.

Thanks,
Abdul

**Comment by Pankraty** [comment]
Sure. `SaveAs()` method can save data not only to the file on disk but also to the stream, and you can open a `MemoryStream` which is sent as a response.

You may also find it convenient to use this lib: https://github.com/ClosedXML/ClosedXML.Extensions.WebApi. It adds an extenstion method for you could simply call `template.Workbook.Deliver("report.xlsx");` after the report is generated.

**Comment by fingers10** [comment]
Thanks for the reply. 

I found a way to generate Excel stream using ClosedXML and return to browser. But the problem is can I achieve the same using ClosedXML.Report? Once I load data and  generate the template how can I get the stream from template? template had only generate method as far as I have seen from report docs. Am I missing something?

Please assist

**Comment by Pankraty** [comment]
Template gives you an access to Workbook property which is the good old ClosedXML workbook which you can operate with.

**Comment by fingers10** [comment]
Really? I'll give a try and paste the complete working sample code here. Please don't close till that. This would be helpful to someone.

**Comment by fingers10** [comment]
Hey Pankraty,

Here is how I return my excel report from asp.net core razor pages.

**Steps:**
1. Button Click in JavaScript:
```js
$('#btnGenerateReport').click(() => {
            window.location.href = '/Index/ExcelReport';
        });
```

2. Page Handler in Asp.Net Core Razor Pages:
```c#
public async Task<IActionResult> OnGetExcelReportAsync()
        {
           var data = await Task.Run(() => get data from db);
            var variable = new ExcelReportModel<ReportModel>
            {
                CompanyName = "Demo",
                Records = data
            };

            return new ExcelReportFromTemplate<ReportModel>(@"wwwroot\templatepath", variable, "DemoReport");
        }
```
3. ExcelReportFromTemplate Action Result:
```c#
public class ExcelReportFromTemplate<T> : IActionResult
    {
        public ExcelReportFromTemplate(string templatePath, object templateVariable, string fileName)
        {
            TemplatePath = templatePath;
            TemplateVariable = templateVariable;
            FileName = fileName;
        }

        public string TemplatePath { get; set; }
        public object TemplateVariable { get; set; }
        public string FileName { get; set; }

        public async Task ExecuteResultAsync(ActionContext context)
        {
                byte[] excelBytes;
                var template = new XLTemplate(TemplatePath);

                template.AddVariable(TemplateVariable);
                template.Generate();
                template.Workbook.Worksheets
                    .Worksheet(template.Workbook.Worksheets.First().Name)
                    .ColumnsUsed()
                    .AdjustToContents();

                using (var stream = new MemoryStream())
                {
                    template.Workbook.SaveAs(stream);
                    excelBytes = stream.ToArray();
                }

                context.HttpContext.Response.Headers["content-disposition"] =
                    $"attachment; filename={FileName}.xlsx";

                await context.HttpContext.Response.Body.WriteAsync(excelBytes, 0, excelBytes.Length);
        }
    }
```
