### ISSUE TITLE
No overload for method 'Relative' takes 2 parameters

### ISSUE THREAD

**Issue by kevlyons** [ClosedXML/ClosedXML.Report#98]
The 2 extension methods called Relative (in XlExtensions.cs), one for IXLRangeAddress (line 132)which takes one parameter IXLRangeAddress; and the other one is for IXLCell (line 147) that takes one parameter IXLAddress.

On line 216 the Intersection Method returns a IXLRangeAddress and tries to call a Range method that takes two parameters! Both of which are IXLRange**Base**, not IXLRange**Address**. 

How are you getting this to compile? I'm trying to compile with Visual Studio 4 Mac.
 
<img width="716" alt="Screen Shot 2019-07-30 at 14 14 30" src="https://user-images.githubusercontent.com/1740222/62100268-64796900-b2d4-11e9-9e75-ead7510cc968.png">

**Comment by b0bi79** [comment]
Check the version of ClosedXML, it should be version 0.95

**Comment by kevlyons** [comment]
Yep, you are right. I had the wrong ClosedXml version. Thx.
