### ISSUE TITLE
{{items.Count()}} in my template gives Unknown identifier 'items' error in excel output

### ISSUE THREAD

**Issue by fingers10** [ClosedXML/ClosedXML.Report#99]
Hi Team,

Thanks for this wonderful Package. I'm using the latest beta.  As per the docs, the following [link](https://closedxml.github.io/ClosedXML.Report/docs/en/Basic-concepts) says, 

> Expressions are enclosed in double braces {{ }} and utilize the syntax similar to C#. Lambda expressions are supported.

`{{items.Where(i => i.Currency == "RUB").Count()}}`

So I tried just to get count from items using `{{items.Count()}}` in my excel template but I'm getting the following error,

> Unknown identifier 'items'

Please assist on where I'm wrong.

**Template:**
![image](https://user-images.githubusercontent.com/43729469/62128808-d6f94180-b2f2-11e9-91a0-d738a78349a3.png)

**Output:**
![image](https://user-images.githubusercontent.com/43729469/62128722-9f8a9500-b2f2-11e9-8eaf-8e0b77be7c5c.png)

Thanks,
Abdul

**Comment by b0bi79** [comment]
@fingers10 Sorry for late answer.
Can you send your template?

**Comment by fingers10** [comment]
> @fingers10 Sorry for late answer.
> Can you send your template?

Here is the template
[CustomerOrdersReport.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3466101/CustomerOrdersReport.xlsx)

Thanks,
Abdul

**Comment by b0bi79** [comment]
1. The range "Records" should also include the options column ([Flat-tables](https://closedxml.github.io/ClosedXML.Report/docs/en/Flat-tables)). Now this used `B7:F8`, but should be `A7:F8`.
2. Out of the range "Records," you can reference it by name. I.e. you need to change the formula in `G4` to `{{Records.Count()}}`

**Comment by fingers10** [comment]
Dear @b0bi79 ,

Thanks for the support. Point 2 worked. And for Point 1, I followed the template requirements in docs and I'm also aware of it. I thought I selected the correct range. But somehow missed it. Thanks for pointing out.

I still have on question as per point 2, if I need to change formula to `{{Records.Count()}}`, then where and when can I use `{{items.Count()}}` as shown in docs?

Thanks,
Abdul

**Comment by b0bi79** [comment]
Inside tables (ranges) you can use:
- the `item` variable to refer to the current row object
- the `items` variable to access the collection
- the `index` variable to get the serial number of the current object in the collection

**Comment by fingers10** [comment]
Any updates regarding the release?

**Comment by b0bi79** [comment]
Я жду релиза ClosedXML.

**Comment by fingers10** [comment]
Alright thanks. Let's close this issue. Thanks for the support and help.
